export const PROMPT_CATEGORIES = [
  {
    id: 'winzer',
    name: 'Winzer & Weinberge',
    icon: '🍇',
    description: 'Edle Tropfen, Weinkeller, sonnige Weinreben und traditionelle Ernte.',
    previewImage: '/previews/winzer.png',
    images: [
      'A sun-drenched vineyard in Tuscany during autumn harvest, golden hour light glowing through ripe purple grapes, morning dew on leaves, cinematic lighting, photorealistic, 8k resolution.',
      'An elderly winemaker with weathered hands holding a glass of deep red wine against a rustic wooden barrel background, warm ambient light, high detail portrait.',
      'Close-up shot of wine being poured into a crystal glass, dynamic splash, dark elegant background, backlit, commercial product photography.',
      'A modern, minimalist wine cellar with concrete walls, glowing warm LED lines highlighting rows of premium bottles, architectural digest style.',
      'A cozy outdoor wine tasting table on a hillside overlooking a misty valley at sunrise, rustic wooden table, two glasses, a bottle, fresh cheese plate.',
      'Close-up of a single green grape bunch on a vine, macro photography, water droplets refracting sunlight, soft bokeh background.',
      'Winemaker inspecting a soil sample in a vineyard, low angle shot, sunrise, lens flare, professional agricultural photography.',
      'An ancient stone wine cellar filled with dusty vintage bottles and oak barrels, soft candlelight, mysterious and historical atmosphere.',
      'A group of friends laughing and cheering with white wine glasses in a lush green vineyard patio during a summer evening sunset, lifestyle photography.',
      'Artistic flat lay of wine bottles, corkscrew, green leaves, grapes, and dried figs on a textured dark slate surface, moody styling.',
      'A professional wine tasting room, clean bright light, white tables with neat rows of tasting glasses, professional sommelier setting.',
      'Harvest season, hands of workers carefully cutting grape bunches from the vine, warm afternoon sun, authentic documentary style.',
      'A stylized, artistic shot of red wine swirling inside a large glass, creating beautiful leg patterns, dark studio setting, dramatic lighting.',
      'A beautiful modern vineyard estate house surrounded by rolling hills, cinematic wide shot, clean blue sky, luxury travel vibe.',
      'A vintage tractor parked between rows of green vines under a dramatic cloudy sunset sky, rustic country aesthetic.',
      'A close-up of a wine cork being pulled out of a bottle, wood texture background, dynamic action freeze frame.',
      'An organic bio-vineyard with wildflowers blooming between the rows, bees flying around, bright sunny day, vibrant colors.',
      'A sommelier in a high-end restaurant decanting red wine, elegant movement, soft dark background, focused lighting on the flow of liquid.',
      'A romantic couple walking hand-in-hand through vineyard paths during golden hour, sun flare, emotional and warm atmosphere.',
      'A bottle of rosé wine chilling in a silver bucket filled with ice cubes, condensation on the bottle, bright summer pool deck background.',
      'A close-up of dark purple grapes covered in morning frost, crystalized ice textures, sunrise glow in the background.',
      'An aerial view of a terraced vineyard climbing a steep mountain slope under a dramatic sky, green and gold leaf patterns.',
      'A rustic wooden table in a vineyard at dusk with a single lit candle, a plate of fresh figs, walnuts, and a bottle of white wine.',
      'Close-up of golden white wine grapes sparkling under sunlight, translucent skins revealing seeds, macro photography.',
      'A modern winemaker examining a glass of red wine in a state-of-the-art laboratory, high-tech equipment and clean steel tanks in background.',
      'A historic stone winery archway with a heavy oak door, covered in green ivy, warm light shining through the window panes.',
      'A close-up of red wine pouring over oak wood, dramatic dark fluid dynamics, studio lighting, splash freeze-frame.',
      'Harvest celebration table outdoors in a vineyard, long table decorated with autumn leaves, glowing lanterns, laughter and wine pouring.',
      'An organic vineyard with sheep grazing between the vine rows, soft morning mist, peaceful and ecological farming scene.',
      'Close-up of a vintner\'s shears cutting a perfect grape bunch from the vine, drops of morning dew flying off.'
    ],
    videos: [
      'Slow motion drone flyover above rolling green vineyard hills at sunrise, mist rising from the valley, cinematic golden light.',
      'Close-up slow motion of red wine pouring into a glass, rich texture, beautiful reflections, 240fps, studio light.',
      'Camera moving through a dark, historic wine cellar, passing wooden barrels illuminated by warm flickering candlelight.',
      'A winemaker gently rotating a wine bottle in a rack, checking the sediment, soft focused lighting, professional motion.',
      'Time-lapse of clouds passing over a beautiful vineyard valley during sunset, colors changing from orange to deep purple.',
      'Close-up of hands picking ripe grapes from the vine, placing them in a wooden basket, warm sunlight filtering through leaves.',
      'Extreme close-up macro shot of dew melting on a grape bunch under the morning sun, glistening water droplets.',
      'A group of people clinking wine glasses in slow motion, laughter, warm ambient lighting, festive outdoor dinner party.',
      'A drone rising up from a single grapevine to reveal a massive, beautiful estate during autumn, vibrant orange and red leaves.',
      'Red wine swirling inside a glass, camera tracking the liquid motion in slow-motion, dark high-contrast background.',
      'Winemaker walking down a row of vines, running his hand gently over the leaves, morning sun behind him, lens flare.',
      'A bottle of sparkling wine being popped open, cork flying, champagne spraying in slow motion, black background, high energy.',
      'Macro shot of wine fermenting in a steel tank, bubbles slowly rising to the surface, industrial winemaking process.',
      'Pouring white wine into a glass on an outdoor table, vineyard view in the blurred background, soft breeze blowing leaves.',
      'Close-up of a wine bottle label being designed or printed, modern high-tech printing press in motion.',
      'Camera panning across a luxury wine tasting table with cheese, grapes, crackers, and multiple glasses of red and white wine.',
      'Workers loading crates of freshly harvested grapes onto a rustic truck, afternoon sun, busy energetic atmosphere.',
      'A wine glass standing on a stone wall in the wind, vineyard landscape stretching into the horizon, calm serene mood.',
      'Detailed shot of a corkscrew twisting into a wooden cork, pulling it out slowly, sound-evoking visual.',
      'Slow motion splash of white wine dropping onto a fresh grape on a reflective black surface, commercial style.',
      'A smooth camera slide along a row of oak wine barrels in a historic cellar, dust dancing in a single beam of light.',
      'Slow motion of white wine being poured into an elegant glass, creating sparkling golden bubbles on the surface.',
      'A drone rising up from a vineyard valley to reveal a beautiful lake in the background at golden hour.',
      'Winemaker holding a handful of dark soil in the vineyard, letting it fall slowly through his fingers, morning sunlight.',
      'Time-lapse of starry night sky over a lonely vineyard estate on a hill, warm glowing windows.',
      'Close-up of a bottle being labeled by an automatic machine in a modern bottling plant, rapid precision movement.',
      'A couple clinking red wine glasses during a romantic picnic in the vineyards, camera slowly zooming out.',
      'Slow motion camera tracking alongside a vintage tractor driving through green grape fields at dawn.',
      'Close-up of red wine droplets slowly running down the side of a clean wine glass, studio lighting.',
      'Workers carefully carrying wooden crates filled with freshly harvested grapes in slow motion, sunny afternoon.'
    ]
  },
  {
    id: 'immo',
    name: 'Immobilienmakler',
    icon: '🏠',
    description: 'Moderne Luxusvillen, gemütliche Innenräume und verkaufsstarke Details.',
    previewImage: '/previews/makler.png',
    images: [
      'Luxury modern villa with glass walls, glowing pool in the foreground, twilight sky, architectural photography, ultra-premium lifestyle.',
      'Bright and airy Scandinavian-style living room, large windows, minimalist furniture, plants, sunny afternoon light, interior design magazine style.',
      'An elegant real estate agent shaking hands with a happy young couple in front of a modern suburban home, warm and welcoming look.',
      'Aerial drone view of a prestigious coastal neighborhood, blue ocean, luxury yachts, sunny day, clean aesthetic.',
      'A cozy farmhouse kitchen with rustic wooden beams, modern copper appliances, warm light, inviting home feel.',
      'Minimalist loft apartment with exposed brick walls, high ceilings, large industrial windows, afternoon light beams.',
      'Close-up of a stylized silver key with a house-shaped keychain resting on a polished wooden table, soft focus background.',
      'A chic modern office space inside a penthouse, panoramic city view through floor-to-ceiling windows at dusk.',
      'An upscale backyard patio with a fire pit, comfortable outdoor sofas, string lights glowing, warm evening vibe.',
      'A real estate agent presenting a house layout on a digital tablet to clients in a bright office, professional and modern.',
      'Beautiful curb appeal of a classic Victorian house, manicured green lawn, blooming flowers, bright sunny day.',
      'Luxurious master bathroom with a freestanding tub, marble walls, gold fixtures, soft spa-like lighting.',
      'A massive walk-in closet in a luxury home, boutique-style lighting, neatly organized designer clothes and shoes.',
      'Modern tiny house in a beautiful forest setting, large glass front, warm lights inside, peaceful nature vibe.',
      'A clean, professional headshot of a real estate agent, confident smile, blurred modern office interior background.',
      'A spacious empty room with light hardwood floors, sunbeams casting shadows on the walls, fresh start feel.',
      'An elegant dining table set for a family dinner in a luxury home, glowing chandelier, warm atmosphere.',
      'A stylish home theater room, plush reclining seats, ambient blue LED lighting, large screen.',
      'A sleek apartment entrance with a smart lock, modern security panel, minimalist design.',
      'Aerial view of a modern green eco-friendly housing development with solar panels and parks, clean future living.',
      'A luxurious modern kitchen with a massive marble island, built-in gold appliances, and soft under-cabinet LED lighting.',
      'An aerial shot of a luxury villa with a private infinity pool overlooking the city skyline at twilight.',
      'A cozy modern nursery room with pastel wooden toys, a soft beige armchair, and warm sunlight filtering through linen curtains.',
      'A stunning home library with dark wooden shelves climbing to a double-height ceiling, a cozy fireplace, and leather armchairs.',
      'A minimalist concrete entryway of a contemporary luxury house, architectural lighting, large pivot door made of dark wood.',
      'A bright, sunny home gym with modern fitness equipment, floor-to-ceiling windows showing a green garden landscape.',
      'A luxury penthouse rooftop terrace at night, glowing fire pit, comfortable lounge sofas, overlooking a lighted cityscape.',
      'Close-up of a high-end smart home touch panel on a wooden wall, displaying climate and lighting controls.',
      'An elegant walk-in wine cellar with custom wooden racks, soft accent lighting, and a small tasting table in the center.',
      'A beautiful modern house exterior clad in natural wood and dark steel, surrounded by tall pine trees, sunny afternoon.'
    ],
    videos: [
      'Smooth cinematic walk-through video entering a luxury villa through double front doors, revealing a massive open-space living room.',
      'Drone flying slowly towards a cliffside mansion at sunset, highlighting the infinity pool and ocean view.',
      'Slow pan across a ultra-modern kitchen, showing high-end appliances, marble countertops, and sunbeams.',
      'A real estate agent turning a key in a lock, opening a modern front door, and gesturing to come inside with a smile.',
      'Time-lapse of natural light moving across a beautifully decorated minimalist living room from morning to evening.',
      'Drone shot rising up from a backyard swimming pool to show a beautiful two-story suburban family home.',
      'A happy family running into their new empty living room, children jumping with joy, emotional lifestyle scene.',
      'Close-up panning shot of luxury bathroom details: water running into a marble tub, soft steam rising.',
      'Cinematic slider shot of a modern home office with a city view, transition from daylight to glowing city lights.',
      'Close-up of a pen signing a housing contract, contract paper, hand movement, professional and decisive.',
      'Slow motion of a couple clinking champagne glasses inside their newly bought modern apartment.',
      'Camera floating through a cozy bedroom with soft linens, curtains gently swaying in a light breeze.',
      'Drone view tracing a long driveway leading up to a grand estate house surrounded by autumn trees.',
      'Interactive 3D-like camera rotation around a sleek kitchen island with fresh flowers and breakfast setup.',
      'A real estate sign in the front yard transitioning from "For Sale" to "SOLD" with a stamp effect.',
      'Camera descending from a high wooden ceiling down to a modern fireplace crackling with warm fire.',
      'A drone shot sweeping over a neighborhood park, showing kids playing and nearby modern family homes.',
      'Slow pan of a smart home interface on a wall screen being touched to dim the living room lights.',
      'A virtual tour style walk-through of a luxury penthouse balcony overlooking a glowing city skyline at night.',
      'Close-up of a house key being placed into a client\'s hand, hand closing gently, emotional moment.',
      'Cinematic slow drone flight around a modern luxury villa showing the outdoor patio and pool deck at twilight.',
      'A smooth camera slider movement showcasing a bright master bedroom with a large window and forest view.',
      'Camera moving slowly through a luxurious home theater, revealing the massive screen and plush leather seats.',
      'A real estate agent placing a "For Sale" sign on a neat green lawn in front of a beautiful family home.',
      'Slow pan across a modern minimalist bathroom with a freestanding tub, soft candles, and marble floor.',
      'Drone rising up to show a stunning eco-friendly apartment building with green vertical gardens on the facade.',
      'Camera gliding through a spacious open-concept kitchen and living room, bathed in bright morning sunlight.',
      'A family unlocking the front door of their new home, stepping inside with excited faces, warm lighting.',
      'Slow motion of water sparkling in a luxury swimming pool, modern villa facade in the background, sunny day.',
      'A real estate agent giving a virtual video tour of a high-end property using a camera gimbal.'
    ]
  },
  {
    id: 'hochzeit',
    name: 'Hochzeit',
    icon: '💍',
    description: 'Romantische Paare, Hochzeitsdeko und emotionale Freudentränen.',
    previewImage: '/previews/wedding.png',
    images: [
      'A romantic bride and groom embracing under a floral arch at sunset, soft golden backlighting, wind blowing veil, emotional fine art photography.',
      'Close-up of wedding rings resting on a delicate white rose petal with tiny dew drops, macro shot, soft pastel bokeh background.',
      'An elegant outdoor wedding reception under fairy lights at night, long wooden tables filled with flowers and candles, magical atmosphere.',
      'The bride getting ready, mirror reflection showing her mother adjusting the wedding dress veil, emotional black and white portrait.',
      'A multi-tiered white wedding cake decorated with fresh pastel flowers and gold leaf details, standing on a rustic wooden table.',
      'The groom looking at the bride walking down the aisle, emotional expression, teary eyes, soft focused background.',
      'An aerial drone shot of a wedding ceremony on a white sandy beach, turquoise water, wooden altar with white drapery.',
      'A bride’s hands holding a lush bouquet of eucalyptus, white peonies, and dusty roses, detailed shot, elegant dress texture.',
      'First dance of a newlywed couple in a grand ballroom, sparkling light reflections, smoke effect on the floor, romantic mood.',
      'A vintage wedding getaway car, classic convertible decorated with flowers and a "Just Married" sign, driving down a scenic road.',
      'Bride and groom walking through a field of lavender at sunset, dreamy pastel colors, cinematic wide shot.',
      'Close-up of a champagne toast, many glasses clinking together, bubbles rising, happy blurred faces in the background.',
      'A beautiful wedding invitation suite laid out on a silk fabric, calligraphy, wax seal, green leaves, flat lay.',
      'Bridal party laughing and tossing flower petals in the air, joyful energy, bright sunny outdoor setting.',
      'A groom adjusting his bow tie in front of a window, soft natural light, focused and sharp portrait.',
      'A dramatic silhouette of a bride and groom kissing inside an ancient church doorway, light beaming in from behind.',
      'An intimate wedding ceremony in a redwood forest, tall trees, sunbeams filtering through leaves, natural rustic setup.',
      'Close-up of the bride\'s shoes and wedding dress lace details resting on a luxurious velvet chair.',
      'A flower girl throwing rose petals down the aisle, cute expression, bright sunlight, soft focus.',
      'A sparkling sparkler exit, guests holding sparklers creating a tunnel for the laughing bride and groom running through.',
      'A beautiful wedding aisle decorated with high pampas grass, white roses, and candles on a wooden floor, indoor ceremony.',
      'Close-up of the groom sliding a sparkling diamond wedding band onto the bride\'s finger, emotional focus.',
      'A joyful bride and groom walking through a shower of white rose petals, laughing, happy guests in background.',
      'An elegant bride standing by a tall palace window, sunbeams illuminating her lace gown and veil, dramatic fine art portrait.',
      'Close-up of a multi-tiered rustic wedding cake with fresh berries, rosemary twigs, and powdered sugar on a wooden slice.',
      'A romantic couple kissing under a grand weeping willow tree adorned with glowing fairy lights at dusk.',
      'A groom laughing with his groomsmen, all wearing classic black tuxedos, holding glasses of whiskey, warm library background.',
      'Close-up of a bride\'s delicate lace garter resting on her leg, soft lighting, elegant bridal detail shot.',
      'An outdoor wedding dinner table under a canopy of stars and hanging green foliage, countless candles glowing.',
      'A bride and groom sharing a quiet moment, foreheads touching, in a sun-drenched field of wildflowers.'
    ],
    videos: [
      'Slow motion of the bride’s veil catching the wind at sunset, golden light illuminating the fabric, romantic camera rotation.',
      'Drone shot flying over a beautiful wedding ceremony setup on a cliff overlooking the ocean during golden hour.',
      'The groom’s emotional reaction as the camera pans to show the bride walking down the aisle in slow motion.',
      'Close-up slow-motion of a champagne cork popping, sparkling wine pouring out, guests cheering in the background.',
      'Slow motion first dance, the groom spinning the bride, her dress swirling, soft fairy lights bokeh in the background.',
      'A camera tracking shot behind the bride and groom as they walk hand-in-hand through a cheering crowd throwing white rose petals.',
      'Macro shot of wedding rings glistening in the sun, slowly rotating on a mirror surface.',
      'Time-lapse of a wedding reception venue being decorated, from empty hall to a magical candlelit dinner setting.',
      'The bride laughing with her bridesmaids as they toast with champagne glasses while wearing matching silk robes.',
      'A romantic slow pan of the wedding table setup, showing flickering candles, elegant plates, and fresh flowers.',
      'Drone shot tracking a classic vintage car driving along a coastal road at sunset with a "Just Married" sign shaking.',
      'Close-up of the bride and groom\'s hands joining together during the vows, soft micro-movements, emotional focus.',
      'A sparkler exit in slow motion, sparks flying, the couple kissing in the middle of the glowing path.',
      'The couple walking through a forest path, sun rays breaking through the trees, camera moving smoothly ahead of them.',
      'Slow motion slice being cut from a beautiful wedding cake, revealing the delicious layers inside.',
      'The bride\'s father wiping a tear from his eye during the wedding speech, authentic emotional documentary style.',
      'Camera panning up from the groom’s polished shoes to his nervous but happy smile in front of the mirror.',
      'A beautiful outdoor altar with white curtains blowing gently in the sea breeze, empty before the ceremony.',
      'Slow motion of the bouquet toss, group of excited women reaching for the flowers in the air.',
      'Romantic kiss under a tree decorated with hundreds of hanging glowing lanterns at night.',
      'Slow motion of the bride and groom clinking champagne glasses at their reception, smiles and blurred lights background.',
      'A drone shot sweeping over an outdoor wedding reception in a Tuscan villa courtyard illuminated by warm string lights.',
      'Slow motion of the bride walking down a forest aisle, sunbeams breaking through the tall trees.',
      'A camera panning across a beautifully arranged wedding dessert table with macarons, cupcakes, and a central cake.',
      'Close-up slow motion of the bride\'s hands holding her bouquet, wind gently moving the silk ribbons.',
      'A romantic couple running away from the camera into a golden wheat field at sunset, laughing and holding hands.',
      'Slow motion of the couple\'s first dance under a shower of falling golden confetti, sparkling light reflections.',
      'Time-lapse of the sun setting behind an altar on a beach, waves gently rolling onto the shore.',
      'Camera tracking behind the newlywed couple walking hand-in-hand out of a historic church, guests cheering.',
      'Slow motion of a wedding sparkler burning, sparks flying in close-up against a dark night background.'
    ]
  },
  {
    id: 'strand',
    name: 'Strandmotive',
    icon: '🏖️',
    description: 'Feiner Sand, türkisfarbenes Wasser, Wellenrauschen und Palmen.',
    previewImage: '/previews/strand.png',
    images: [
      'A pristine tropical beach with crystal clear turquoise water, white sand, coconut palm trees leaning over the sea, sunny paradise vibe, 8k.',
      'A dramatic sunset over a stormy ocean, dark purple clouds, glowing orange horizon, waves crashing on black volcanic sand.',
      'Close-up of a beautiful seashell half-buried in wet sand, a gentle wave washing over it, macro shot, morning sunlight.',
      'A lone hammock tied between two palm trees on a secluded island beach, overlooking a calm blue lagoon, relaxing mood.',
      'An aerial drone shot of footprints leading into the ocean on a golden beach, perfect symmetry, minimal aesthetic.',
      'A rustic beach bonfire at twilight, sparks flying into the starry sky, cozy blankets and surfboards nearby.',
      'A tropical cocktail in a coconut with a straw, resting on a beach towel, sunny ocean background, refreshing summer vibe.',
      'A surfer carrying a surfboard walking towards massive waves at sunrise, mist on the water, high contrast silhouette.',
      'A wooden pier stretching far into a calm pastel-colored ocean at dawn, pink and purple sky, serene landscape.',
      'A tidal pool filled with colorful starfish and sea anemones on a rocky coast, clear water, bright day.',
      'A luxury beach villa patio with comfortable loungers, open to a private white sand beach and calm sea.',
      'A close-up of dynamic ocean waves breaking, capturing the transparent blue-green tube of water, sunlight shining through.',
      'A romantic picnic setup on the beach at sunset, low wooden table, cushions, wine, candles, warm ocean breeze.',
      'A flock of seagulls flying low over a sandy beach during a bright windy afternoon, dynamic motion.',
      'A child building a sandcastle on the shore, warm sunlight, soft bokeh of waves in the background.',
      'An exotic black sand beach in Iceland, dramatic basalt columns, white sea foam crashing, moody atmospheric look.',
      'A classic beach cruiser bicycle parked in the sand dunes with sea oats blowing in the wind, sunny retro vibe.',
      'Close-up of feet stepping into warm sandy beach water, ripples in the water, relaxing summer feel.',
      'A majestic sea turtle swimming over a vibrant coral reef near a sunny beach shore, underwater split-shot.',
      'A lighthouse standing tall on a grassy cliff overlooking a vast ocean under a clear blue sky.',
      'A high-end beach cabana with white blowing curtains, looking out over a calm turquoise ocean, luxury resort vibe.',
      'A pink sand beach at sunrise, pastel pink and orange sky, gentle waves leaving white foam on the shore.',
      'Close-up of a colorful starfish resting on a wet rock, tide pool water reflecting the sunny sky.',
      'A surfer sitting on a surfboard in the ocean, waiting for a wave during a golden sunset, silhouette.',
      'A majestic archway formed by coastal cliffs over the ocean, waves crashing through it, bright sunny day.',
      'A cozy bonfire on the sand dunes at twilight, wooden logs, warm glow, sea oats blowing in the wind.',
      'Aerial shot of a coral reef near a sandy beach, clear water revealing underwater marine life and patterns.',
      'A retro surf van parked on a sandy beach under palm trees, surfboards on top, sunny summer afternoon.',
      'Close-up of wet sand showing tiny details of shells, pebbles, and water ripples left by a retreating wave.',
      'A lighthouse sitting on a grassy cliff overlooking a stormy dark ocean with huge waves crashing.'
    ],
    videos: [
      'Cinematic drone shot flying low over the shoreline, crystal clear waves gently rolling onto pristine white sand.',
      'Time-lapse of a breathtaking tropical sunset, sky transitioning from yellow to deep pink, sun dipping below the ocean horizon.',
      'Close-up slow-motion of a wave breaking, capturing the crystal-clear water tube and white foam splashing.',
      'Camera moving forward underneath palm leaves swaying in a tropical breeze, revealing a beautiful sunny beach.',
      'A cozy beach bonfire burning at night, sparks drifting up, sound of crashing waves implied visually.',
      'Aerial top-down view of turquoise water clashing with white sand, creating beautiful natural patterns.',
      'A surfer paddling out into the ocean during a golden sunrise, misty water surface, epic scale.',
      'Slow pan across a romantic beach picnic setup at dusk, candles flickering, waves in the background.',
      'Footprints in the wet sand being slowly washed away by a gentle incoming wave in slow motion.',
      'Underwater camera swimming alongside colorful tropical fish and a sea turtle near a sandy shore.',
      'Time-lapse of tide pools filling up with ocean water as the tide comes in over dark coastal rocks.',
      'Camera tracking a person walking along the beach at sunrise, holding sandals in hand, peaceful morning walk.',
      'A luxury beach resort infinity pool blending seamlessly with the ocean at twilight, lights turning on.',
      'A storm approaching the beach, dark heavy clouds, strong wind blowing sand dunes, dramatic energy.',
      'Close-up of a cold tropical drink sweating with condensation, sun shining through the glass, beach background.',
      'Slow motion of colorful kites flying high above a crowded, sunny summer beach.',
      'A drone rising up from a historic lighthouse to reveal a massive rocky coastline and crashing waves.',
      'A hammock gently swaying between two palms as the sun sets in the background, creating a silhouette.',
      'Crabs running across wet sand, ducking into small holes as a wave approaches, macro tracking shot.',
      'Gentle mist spraying from a big wave hitting a cliff, rainbow forming in the mist under the sun.',
      'Drone shot tracking a surfer riding a big blue wave, capturing the speed and water spray in slow motion.',
      'Slow pan across a peaceful beach at dawn, misty water, pastel pink clouds, serene atmosphere.',
      'Close-up slow motion of a person\'s hand running through dry, warm beach sand, grains falling down.',
      'A time-lapse of tide water slowly rising around a lonely rock on a sandy beach, sun setting.',
      'Drone flying low under palm trees along a tropical coast, revealing a private beach and turquoise water.',
      'Slow motion of a dog running joyfully along the shoreline, splashing water under a bright sun.',
      'Time-lapse of clouds passing over a classic coastal lighthouse during a windy, bright afternoon.',
      'Close-up of water splashing over sea glass on the shore, glistening in the sun, macro video.',
      'Camera moving through sea oats on sand dunes at sunset, revealing a wide view of the quiet beach.',
      'Slow motion of a tropical rain shower hitting the ocean surface, creating beautiful tiny ripples and mist.'
    ]
  },
  {
    id: 'urlaub',
    name: 'Urlaubsmotive',
    icon: '✈️',
    description: 'Roadtrips, fremde Kulturen und weltberühmte Aussichtspunkte.',
    previewImage: '/previews/urlaub.png',
    images: [
      'A traveler standing on the edge of a cliff in Norway, looking at a massive fjord below, epic scale, sunny day, adventure travel.',
      'A cozy wooden cabin in the Swiss Alps covered in snow, warm lights glowing inside, smoking chimney, starry winter night.',
      'A classic Vespa scooter parked in a narrow, flower-filled street in Santorini, white houses, blue domes, bright sunny day.',
      'An infinity pool overlooking the jungle in Bali at sunrise, mist rising from the trees, luxury resort vibe.',
      'A hot air balloon flight over Cappadocia at dawn, hundreds of balloons in the sky, unique rocky landscape.',
      'A traditional wooden boat floating on a crystal clear lake in the Dolomites, surrounded by towering mountain peaks.',
      'A bustling colorful market street in Marrakech, spices stacked in cones, lanterns glowing, rich textures.',
      'A traveler reading a book on a balcony overlooking the Eiffel Tower in Paris, morning coffee and croissants on the table.',
      'An old train winding through lush green tea plantations in Sri Lanka, mist, vintage travel aesthetic.',
      'A luxury glamping tent in the middle of the desert under a clear Milky Way galaxy sky, glowing campfire.',
      'A highway stretching through the red rock desert of Route 66, USA, road trip vibe, endless horizon.',
      'A close-up of a passport with stamps and boarding passes resting on a wooden vintage suitcase, wanderlust concept.',
      'A couple kayaking in a glowing bio-luminescent bay at night, magical blue water glowing under their paddles.',
      'A quiet canal in Venice in the morning, gondola parked by historic stone walls, soft reflection in the water.',
      'A surfer overlooking a lush green coastline and breaking waves in Hawaii, tropical adventure vibe.',
      'A beautiful traditional ryokan room in Kyoto, open sliding doors showing a zen garden with autumn maple leaves.',
      'A modern camper van parked on a cliff overlooking the ocean at sunset, bonfire burning next to it, vanlife.',
      'A hike through a bamboo forest in Japan, sunbeams filtering through the tall green stalks, serene nature shot.',
      'An epic wide shot of the Taj Mahal at sunrise, pink mist over the reflecting pool, majestic travel icon.',
      'A traveler swimming in a hidden cenote cave in Mexico, sunbeam shining through a hole in the ceiling onto the blue water.',
      'A classic vintage train window view overlooking a dramatic green valley and ancient stone bridges, misty mountains.',
      'A cozy café table in a historic Parisian street, a cup of coffee, a fresh croissant, and a travel map, sunny day.',
      'A traveler overlooking the ancient ruins of Machu Picchu from a mountain peak, dramatic clouds, epic scale.',
      'A luxury overwater bungalow in the Maldives, private steps leading into turquoise water, clear sunny sky.',
      'Close-up of a person\'s hand holding a compass over a topographical map, planning a hiking route, rustic table.',
      'A colorful hot air balloon floating close to the ground in a desert landscape, glowing burner fire.',
      'A historic street in Kyoto at night, glowing wooden lanterns, traditional wooden houses, soft rain reflecting lights.',
      'A traveler swimming in a crystal clear cenote cave in Mexico, tropical plants hanging from the ceiling opening.',
      'A camper van parked on a cliff overlooking a massive fjord in Norway at sunset, campfire burning next to it.',
      'A beautiful infinity pool overlooking the green rice terraces of Ubud, Bali, at early morning sunrise.'
    ],
    videos: [
      'Cinematic drone flyover of a hot air balloon rising over the unique rock formations of Cappadocia at sunrise.',
      'First-person view walking through a narrow, colorful street in an Italian coastal village, locals waving, sunny day.',
      'Slow motion of a train window view passing through lush green mountains and misty forests in Asia.',
      'Drone shot diving down a massive waterfall in Iceland, spray hitting the camera, epic adventure feel.',
      'A camper van driving along a winding coastal highway at sunset, camera tracking from behind.',
      'Time-lapse of the northern lights dancing over a cozy wooden cabin in a snowy forest in Lapland.',
      'Slow pan across a luxury resort balcony breakfast setup, revealing a panoramic view of the Amalfi coast.',
      'Underwater camera swimming into a deep blue cenote cave, light rays shifting in the water.',
      'A person jumping off a wooden pier into crystal clear tropical water, splashing in slow motion.',
      'Drone shot flying through a deep canyon in Utah, red rock walls towering on both sides.',
      'Time-lapse of stars moving across the sky above a tent in a sand dune desert, campfire glowing.',
      'First-person view kayaking through calm turquoise waters between massive limestone cliffs in Thailand.',
      'A camera tracking shot of a traveler walking through a bustling night market in Tokyo, neon lights reflecting.',
      'A traditional boat moving slowly through a misty lake in the mountains at dawn, water ripples.',
      'Slow motion of autumn leaves falling in a historic park in London, tourists walking in the background.',
      'A drone rising up from a swimming pool to show a luxury cliffside villa overlooking the Mediterranean sea.',
      'A hiker reaching the summit of a mountain, raising arms in triumph, wind blowing, panoramic view.',
      'Close-up of a map being unfolded on a car hood, fingers tracing a route, road trip preparation.',
      'A gondola gliding smoothly through a quiet Venice canal under a stone bridge, morning sun.',
      'Slow motion of waves hitting the wheels of a beach buggy driving on a sandy coast at sunset.',
      'Drone shot tracking a red train winding through a lush green pine forest in the Swiss Alps, snow peaks background.',
      'Slow motion of a traveler walking through a bustling marketplace in Marrakech, touching colorful fabrics.',
      'A first-person view walking along a wooden pier in the Maldives, turquoise water on both sides, sunny day.',
      'Time-lapse of stars rotating over a camper van parked in the desert, glowing campfire in front.',
      'Slow motion of a traveler jumping into a deep blue ocean from a yacht, water splashing in the sun.',
      'Camera tracking a hiker reaching a mountain summit, raising hands, wind blowing, wide scenic view.',
      'Drone shot flying down a deep canyon with a winding river at the bottom, red rock walls, sunny day.',
      'Slow motion of colorful hot air balloons rising over Cappadocia, sun flare breaking through the balloons.',
      'Camera panning across a luxurious balcony breakfast table overlooking the ocean on a sunny morning.',
      'First-person view kayaking through a quiet mangrove forest, water ripples, exotic birds flying above.'
    ]
  },
  {
    id: 'lostplaces',
    name: 'Lost Places',
    icon: '🏚️',
    description: 'Verfallene Säle, überwucherte Ruinen und mystischer Verfall.',
    previewImage: '/previews/lost.png',
    images: [
      'An abandoned grand ballroom with a decaying crystal chandelier hanging from a cracked ceiling, dust motes dancing in sunbeams, eerie beauty.',
      'A rusted steam locomotive overgrown with green ivy and wildflowers inside a collapsed train depot, nature reclaiming technology.',
      'A forgotten library with decaying books scattered on the floor, moss growing on wooden bookshelves, light streaming through a broken stained-glass window.',
      'An empty amusement park at twilight, a rusted Ferris wheel silhouetted against a moody dark purple sky, overgrown weeds.',
      'An abandoned glass greenhouse, half-broken glass panels, overgrown tropical plants bursting out, soft misty atmosphere.',
      'A decaying retro diner from the 1950s, dust-covered jukebox, cracked leather booths, sun rays highlighting peeling paint.',
      'An empty theater stage with velvet curtains rotting away, a single spotlight beam of sunlight hitting an old wooden chair.',
      'An abandoned industrial factory floor, massive rusted pipes, broken machinery, moss carpet on the concrete floor, high contrast lighting.',
      'A forgotten mansion hallway with peeling wallpaper, cracked mirrors reflecting dust, a grand staircase covered in debris.',
      'An old classroom with a dusty blackboard still showing chalk writings from decades ago, small wooden desks, moody lighting.',
      'An abandoned shipwreck stranded on a rocky coast, rusted hull, waves crashing against it, dramatic overcast sky.',
      'A decaying vintage car parked inside an overgrown wooden barn, sunbeams piercing through gaps in the wood walls.',
      'An empty mental asylum ward, peeling paint on walls, rusted metal bed frame in the center, creepy atmospheric look.',
      'An abandoned stone cottage in a dense forest, roof collapsed, trees growing inside the living room, fantasy aesthetic.',
      'A forgotten underground subway station, rusted tracks, peeling posters from the 80s, eerie green emergency lighting.',
      'An old piano standing in the middle of a decaying church, dust layers on keys, light beaming from a high window.',
      'An abandoned observatory, massive telescope pointing at a sky visible through a collapsed dome roof, starry night.',
      'A decaying control room of a Soviet-era power plant, analog dials and buttons covered in dust and rust, cold war relic.',
      'An overgrown stone staircase leading to nowhere in a deep dark forest, covered in thick green moss, mysterious mood.',
      'A forgotten villa bedroom, a dusty canopy bed, rotting fabrics, old photos scattered on the floor, nostalgic sadness.',
      'An abandoned classical theater stage with rotting red velvet curtains, light beam hitting a dusty microphone stand.',
      'A rusted vintage car covered in dry autumn leaves inside a collapsed wooden barn, sunbeams piercing the roof.',
      'An overgrown stone staircase leading down into a dark forgotten cellar of a medieval ruin, green moss.',
      'An empty abandoned library room with giant windows, moss growing on the floor, books piled like towers.',
      'An abandoned control room of an old factory, rusted dials, analog meters, wires hanging from the ceiling.',
      'A decaying greenhouse with broken glass panels, overgrown with wild ferns and tropical plants, misty morning light.',
      'An abandoned classroom with a dusty blackboard showing old chalk formulas, small wooden chairs in disarray.',
      'A forgotten stone chapel in the forest, collapsed roof, a tree growing in the center aisle, soft light beams.',
      'An abandoned hospital ward at dusk, rusted metal beds, peeling paint on walls, spooky shadow play.',
      'A rusted Ferris wheel in an overgrown abandoned amusement park, silhouetted against a dramatic purple twilight sky.'
    ],
    videos: [
      'Slow cinematic drone shot flying through a broken window into a decaying, overgrown grand ballroom.',
      'Camera moving slowly down a long, dark asylum corridor, peeling paint on walls, dust particles floating in light beams.',
      'Time-lapse of moss and ivy growing over a rusted typewriter on a dusty desk near a broken window.',
      'A slow pan across an abandoned amusement park, showing a rusted Ferris wheel creaking slightly in the wind.',
      'Drone shot flying over a massive rusted shipwreck stuck on a rocky shore, ocean waves crashing in slow motion.',
      'Camera slowly pushing in on a dusty old piano in a decaying hall, a single key slowly falling down on its own (spooky vibe).',
      'Walking view exploring an abandoned underground bunker, flashlight beam cutting through the pitch-black darkness.',
      'A slow tracking shot along rusted machinery in a massive, silent industrial factory, nature reclaiming the space.',
      'Time-lapse of light and shadows moving across a forgotten classroom with old wooden desks and a dusty blackboard.',
      'A drone rising up through the collapsed roof of an old church, revealing the forest surrounding the ruins.',
      'Camera panning down from a broken glass greenhouse dome to show wild ferns growing over rusty tables.',
      'Slow motion of dust swirling in a bright sunbeam inside a decaying library filled with rotting books.',
      'A slow slider shot of a rusted retro car covered in leaves inside a collapsing wooden garage.',
      'Walking down a grand staircase in a decaying mansion, debris crunching underfoot (implied audio), moody shadows.',
      'Camera rotating around a single rusted swing set moving slowly in the wind in an empty overgrown playground.',
      'A drone shot flying low along abandoned train tracks that disappear into a dark, overgrown forest tunnel.',
      'An old analog clock on a decaying wall, hands frozen, camera slowly zooming in on the dusty clock face.',
      'Slow pan of a forgotten theater hall, stage curtains swaying gently in a draft, light shining on dust.',
      'Exploring an old castle ruin at dusk, flashlight beam illuminating ancient stone carvings covered in moss.',
      'A slow tilt shift video of a abandoned radar station on a mountain peak, clouds passing rapidly behind it.',
      'Drone shot flying slowly through the collapsed roof of an old industrial building, revealing overgrown machinery.',
      'A slow pan across an abandoned library, showing dust motes dancing in a single strong sunbeam.',
      'Camera tracking along rusted train tracks that disappear into a dark overgrown forest tunnel.',
      'Slow motion of dust swirling around an old piano in a decaying hall, soft wind blowing curtains.',
      'Walking view with a flashlight cutting through the dark corridor of an abandoned underground bunker.',
      'Time-lapse of light and shadows moving across a decaying bedroom in a forgotten mansion, peeling wallpaper.',
      'Drone shot circling a rusted shipwreck stranded on a rocky shore, ocean waves crashing in slow motion.',
      'Slow motion zoom on a frozen old clock on a dusty decaying wall, rust and cobwebs.',
      'Camera moving slowly down a long dark corridor of an old mental asylum, doors half-open.',
      'Slow pan of an overgrown swing set in an empty playground, moving slightly in the wind.'
    ]
  },
  {
    id: 'schloesser',
    name: 'Schlösser & Burgen',
    icon: '🏰',
    description: 'Thronsäle, historische Innenhöfe und sagenhafte Festungen.',
    previewImage: '/previews/burg.png',
    images: [
      'A majestic medieval castle standing on a high cliff surrounded by autumn forests, morning mist, dramatic sunbeams, epic fantasy style.',
      'A luxury fairytale palace reflecting in a perfectly calm lake at sunset, pink and gold sky, elegant spires and towers.',
      'An ancient stone castle courtyard at night, torches lit, glowing windows, mysterious medieval atmosphere, starry sky.',
      'The grand library of a royal palace, tall wooden shelves filled with leather-bound books, rolling ladders, warm classical lighting.',
      'A ruined gothic castle under a dramatic thunderstorm sky, lightning bolt striking in the background, dark moody fantasy.',
      'The throne room of an emperor, golden ornaments, red velvet carpets, massive throne under a high arched window, cinematic.',
      'An aerial drone shot of a star-shaped renaissance fortress surrounded by a water moat, green lawns, symmetrical geometry.',
      'A grand dining hall in a castle, a long banquet table set with silver plates, candlesticks glowing, medieval feast vibe.',
      'A castle drawbridge lowering over a misty moat at sunrise, sun flare reflecting off the wet wood and iron chains.',
      'Close-up of a medieval stone fireplace crackling with fire inside a cozy castle chamber, tapestries on the walls.',
      'A winding stone spiral staircase inside a castle tower, light beaming from a narrow slit window, high contrast shadows.',
      'A beautiful white palace surrounded by manicured French gardens, fountains spraying water, bright sunny day, Versailles style.',
      'A historic castle gate guarded by stone gargoyles, iron portcullis half-open, misty forest pathway leading to it.',
      'The ruins of a hilltop castle at sunset, only stone arches standing, sky turning orange and red, cinematic silhouette.',
      'A royal bedroom in a palace, a four-poster gold bed with silk curtains, elegant classical paintings on the ceiling.',
      'A misty bridge leading to a fairytale castle in the middle of a lake, mystical fantasy mood, reflection on water.',
      'An ancient armory hall inside a castle, rows of shining knight armors holding swords, dim torchlight.',
      'A palace ballroom with polished marble floors reflecting crystal chandeliers, high gold-trimmed mirrors, royal elegance.',
      'A hidden secret door disguised as a bookshelf inside an old castle study, half-open, dark room visible behind.',
      'A dramatic winter shot of a castle covered in snow, standing tall against a dark blue twilight sky, warm lights in windows.',
      'A majestic castle perched on a snow-covered mountain peak, glowing warm windows against a dark blue twilight sky.',
      'An imperial throne room with golden ornaments, red velvet carpets, and a large throne under arched windows.',
      'An ancient castle courtyard at night, stone walls illuminated by burning torches, starry sky above.',
      'A grand castle dining hall with a long table set with silver plates, candles glowing, medieval feast vibe.',
      'A ruined hilltop castle at sunset, stone arches silhouetted against a dramatic orange and red sky.',
      'A beautiful white palace surrounded by manicured French gardens, fountains spraying water, sunny day.',
      'A winding stone spiral staircase inside a castle tower, light beaming from a narrow slit window.',
      'An ancient armory hall inside a medieval castle, rows of shining knight armors holding swords, dim lighting.',
      'A castle drawbridge half-lowered over a misty moat at sunrise, golden sun reflection.',
      'A palace ballroom with polished marble floors reflecting crystal chandeliers, gold-trimmed walls.'
    ],
    videos: [
      'Drone flyover of a fairytale castle perched on a rocky mountain peak, fog drifting through the valley below at sunrise.',
      'Camera walking slowly through a grand palace corridor, passing massive paintings, gold frames, and marble columns.',
      'Drone shot descending into a castle courtyard, revealing a medieval market setup or knights preparing.',
      'A slow cinematic pan across a royal throne room, lighting up the golden details as sun rays break through the window.',
      'Time-lapse of a starry night sky moving above the ruins of a gothic castle on a hill.',
      'A camera tracking shot walking up a winding stone spiral staircase inside a castle tower, torch flickering.',
      'Drone view flying low over a palace water moat, reflecting the majestic castle towers in the morning light.',
      'Slow motion of a heavy iron drawbridge closing, chains rattling, dust rising from the stone ground.',
      'A slow pan of a grand palace ballroom, capturing the reflection of glowing chandeliers on the polished marble floor.',
      'Drone shot sweeping over a massive star fortress, highlighting the green grassy ramparts and surrounding water.',
      'A camera moving through the royal library, passing ancient books and a cozy fireplace burning in the corner.',
      'Lightning striking behind a ruined dark castle on a cliff, creating a dramatic and spooky silhouette.',
      'A slow tilt-up from a stone gargoyle statue to the massive wooden entrance gate of a medieval fortress.',
      'Camera floating through a castle garden maze, green hedges, revealing a beautiful palace in the center.',
      'Slow motion of a fire crackling in a massive stone fireplace inside a royal dining chamber.',
      'A drone shot circling a snow-covered castle at dusk, warm yellow lights glowing in the towers.',
      'A close-up of a wax seal being stamped onto a royal decree document inside a castle study room.',
      'Time-lapse of clouds moving rapidly over a cliffside castle during a colorful sunset.',
      'Camera tracking a person in a historical royal gown walking through a palace hallway, dress sweeping the floor.',
      'A slow dolly shot entering the armory hall, rows of knight armors standing in silent formation.',
      'Drone shot circling a snow-covered castle at dusk, warm yellow lights glowing in the towers.',
      'A slow cinematic pan across a royal throne room, lighting up golden details as sun rays break through.',
      'A camera tracking shot walking up a winding stone spiral staircase inside a dark castle tower, torch flickering.',
      'Time-lapse of clouds moving rapidly over a cliffside castle during a colorful sunset, dramatic colors.',
      'Drone shot descending into a castle courtyard, revealing a medieval market setup in slow motion.',
      'Camera floating through a castle garden maze, green hedges, revealing a beautiful palace in the center.',
      'Slow motion of a fire crackling in a massive stone fireplace inside a royal dining chamber.',
      'Drone flyover of a fairytale castle perched on a rocky mountain peak, fog drifting through the valley.',
      'Camera tracking a person in a historical royal gown walking through a palace hallway, dress sweeping.',
      'A slow dolly shot entering the armory hall, rows of knight armors standing in silent formation.'
    ]
  },
  {
    id: 'food',
    name: 'Food & Gastronomie',
    icon: '🍔',
    description: 'Köstliche Nahaufnahmen, dampfende Gerichte, edle Restaurant-Atmosphäre.',
    previewImage: '/previews/food.png',
    images: [
      'A modern restaurant dining table with a beautifully plated gourmet dish, fresh herbs, microgreens, drizzled sauce, warm atmospheric lighting, professional food photography.',
      'Close-up of a juicy hamburger with melting cheddar cheese, fresh lettuce, and tomatoes, steam rising, macro shot, commercial product look.',
      'Artistic slow drippings of golden maple syrup onto a stack of fluffy pancakes with fresh blueberries on top, bright morning light.',
      'A dark moody shot of a chocolate soufflé being cut open with a spoon, warm liquid chocolate oozing out, powdered sugar dusting.',
      'Sushi rolls neatly arranged on a black slate platter, chopsticks holding one roll, green wasabi and ginger in the background, elegant Japanese restaurant vibe.',
      'A rustic wooden table with a bowl of hot ramen, steam rising, chopsticks lifting noodles, soft ambient light.',
      'Close-up of a fresh chocolate chip cookie being pulled apart, warm gooey chocolate stretching between halves.',
      'An elegant cheese platter with brie, grapes, walnuts, honey jar, and crackers on marble, dark background.',
      'Close-up of a perfectly seared steak resting on a wooden board, rosemary twig, sea salt flakes, herb butter melting.',
      'A bright, fresh summer salad with strawberries, goat cheese, avocado, and balsamic dressing, sunny afternoon light.',
      'A professional flat lay of raw baking ingredients: flour dust, eggs, rolling pin, and chocolate chunks on black stone.',
      'Freshly baked sourdough bread with a crispy golden crust, steam rising from a cut slice, rustic bakery setting.',
      'An artistic dessert plate with raspberry macaron, vanilla ice cream scoop, fresh mint, and red fruit sauce drippings.',
      'A steaming cup of cappuccino on a wooden table, perfect latte art heart, coffee beans scattered around, warm café light.',
      'Close-up of honey drizzling slowly from a wooden dipper onto fresh waffles, golden light reflecting.',
      'A luxury seafood platter with oysters on ice, fresh lemon slices, lobster tail, white wine glass in background.',
      'A close-up of colorful Italian gelato scoops in a waffle cone, melting drops, bright summer pool background.',
      'A modern bowl of avocado toast with poached egg on top, running golden yolk, chili flakes, bright breakfast light.',
      'A professional chef garnishing a gourmet plate with micro herbs using tweezers, high-end restaurant kitchen.',
      'Close-up of fresh red strawberries being dipped into dark melted chocolate, smooth satin liquid texture.',
      'A rustic copper pot filled with bubbling red tomato pasta sauce, fresh basil leaves, steam rising.',
      'A stack of fresh chocolate donuts with rainbow sprinkles on a pink plate, bright pop-art style lighting.',
      'A close-up of a sharp knife slicing through a ripe avocado, creamy green texture, clean minimalist background.',
      'Traditional Spanish paella in a rustic pan, large shrimp, mussels, lemon wedges, outdoor sunny terrace.',
      'Close-up of a cold beer mug with thick white foam, condensation droplets running down the glass, pub light.',
      'A plate of freshly prepared tacos with pulled beef, cilantro, lime, and red onions, vibrant mexican colors.',
      'An elegant tea setting with a porcelain teapot, a cup of steaming green tea, lemon slice, soft morning light.',
      'Close-up of olive oil being poured onto fresh mozzarella and tomatoes, glossy surface, macro shot.',
      'A rustic cutting board with fresh garlic bulbs, red chili peppers, rosemary, and olive oil bottle, dark moody lighting.',
      'A beautiful charcuterie board filled with cured meats, olives, almonds, and bread slices, warm party atmosphere.'
    ],
    videos: [
      'Slow motion of a chef slicing fresh vegetables on a wooden cutting board, steam rising in the background, sharp knife motion.',
      'Panning shot of a premium wood-fired pizza being pulled out of a brick oven, bubbling cheese and smoking crust.',
      'Extreme close-up of coffee dripping into a glass cup in slow motion, rich crema forming, warm café atmosphere.',
      'Sparkling white wine being poured into a tall glass next to a fresh seafood plate on an outdoor table.',
      'A pastry chef dusting powdered sugar onto a freshly baked chocolate cake in slow motion, sugar particles floating in the light.',
      'Slow motion of chocolate syrup being drizzled over vanilla ice cream scoop, rich dark liquid flow.',
      'Close-up slow motion of a knife cutting a crispy baguette, crumbs flying off in bright light.',
      'Time-lapse of dough rising inside a warm oven, crust browning and turning golden.',
      'Slow motion of red wine pouring into a decanter, oxygenating, elegant swirling fluid motion.',
      'A chef flipping a colorful stir-fry in a wok over a high flame, fire flare, fast energetic movement.',
      'Close-up of honey dripping from a wooden spoon onto pancakes in slow motion, soft sunlight.',
      'Pouring hot milk into coffee, creating a beautiful swirling marble pattern, slow motion.',
      'Slow motion of a juicy burger being squeezed, melting cheese and sauce dripping down.',
      'A pastry chef decorating a wedding cake with fresh berries, precise camera movement.',
      'Close-up of salt flakes falling onto a seared steak in slow motion, dark high contrast background.',
      'Time-lapse of ice melting in a cold glass of soda, bubbles rising rapidly to the surface.',
      'Slow motion of fresh pasta being dropped into boiling water, bubbles splashing.',
      'A close-up of a sommelier opening a champagne bottle, soft smoke releasing from the cork opening.',
      'Slow motion of colorful macarons falling onto a soft pink surface, bouncing gently.',
      'A chef grilling steaks on an outdoor barbecue, smoke rising, flames licking the meat, slow motion.',
      'Camera tracking close to a knife slicing fresh red salmon sushi, chef\'s professional movements.',
      'Slow motion of hot soup being ladled into a rustic ceramic bowl, steam swirling.',
      'Close-up of cheese stretching from a hot slice of pizza being lifted, slow motion.',
      'A camera panning across a vibrant farmers market stall filled with fresh organic vegetables.',
      'Slow motion of powdered sugar being sifted onto fresh waffles, white dust floating in light.',
      'A close-up of dynamic splash of orange juice pouring into a glass, slow motion.',
      'Camera moving through a high-end restaurant kitchen during a busy evening dinner service.',
      'Slow motion of fresh berries falling into a bowl of creamy yogurt, creating soft splashes.',
      'Close-up of garlic cloves being crushed by a knife on a wooden cutting board.',
      'Slow motion of a chocolate fountain flowing, rich smooth dark chocolate dripping.'
    ]
  },
  {
    id: 'fitness',
    name: 'Fitness & Sport',
    icon: '🏋️',
    description: 'Dynamisches Training, Athleten im Fokus, energiegeladene Gym-Szenen.',
    previewImage: '/previews/fitness.png',
    images: [
      'An athletic person tying shoelaces in a modern gym, soft dramatic volumetric lighting, focus on sports shoes, energetic mood, photorealistic.',
      'A fitness athlete in mid-air performing a box jump, dynamic motion freeze, sweat drops in the air, high contrast gym lighting.',
      'Close-up of chalked hands gripping a heavy barbell, preparing for a lift, raw power and focus, gritty industrial gym style.',
      'A runner sprinting along a misty river path at dawn, silhouette against the rising sun, orange lens flare, active life concept.',
      'A peaceful yoga session in a bright sunlit studio, plants in the background, soft warm colors, calm serene atmosphere.',
      'A female athlete training with heavy battle ropes, intense expression, sweat drops flying, dark industrial gym.',
      'A close-up of running shoes hitting the asphalt, water splashing from a puddle, sunset lighting, motion freeze.',
      'An outdoor street workout athlete performing a human flag on metal bars, blue sky background, peak physical form.',
      'Close-up of a swimmer diving into a clear blue pool, water splashing, underwater action perspective.',
      'A male gymnast performing a handstand on rings, focused face, muscular definition, dark dramatic studio.',
      'A cyclist riding up a steep mountain pass at dawn, misty valleys below, active lifestyle motivation.',
      'Close-up of hands pulling a rowing machine handle, veins visible, sweat, hard training focus.',
      'A female tennis player serving the ball, dynamic motion freeze, tennis court clay flying, sunny day.',
      'A mountain climber hanging from a steep rock cliff, majestic mountain peaks in the background, extreme sport.',
      'A group of athletes running together on a forest track at sunrise, sun rays breaking through trees.',
      'A female boxer training with speed bag, fast motion blur, determined eyes, focused athletic portrait.',
      'A yoga practitioner in crow pose on a wooden deck by a calm lake, misty morning atmosphere.',
      'Close-up of a heavy kettlebell resting on a gym floor, chalk dust particles floating in a light beam.',
      'An athlete sprinting up a long outdoor concrete staircase, low angle shot, dynamic energy.',
      'A personal trainer showing a client proper deadlift form, modern gym background, supportive atmosphere.',
      'A close-up of a smart watch displaying heart rate and active calories on a sweaty wrist during running.',
      'A crossfit athlete flipping a massive tire outdoors, intense effort, muscles tensed, grit style.',
      'A female dancer jumping high in a bright loft studio, graceful fluid motion, sunlight pouring in.',
      'A basketball player shooting a ball towards a hoop at sunset, perfect silhouette action shot.',
      'Close-up of water splashing onto a runner\'s face, refreshing cooling effect, dramatic lighting.',
      'A weightlifter celebrating after a successful clean and jerk, screaming with joy, lifting platform.',
      'A female athlete stretch training on a yoga mat, warm afternoon sun casting long shadows.',
      'Close-up of dynamic running tracks on a red outdoor stadium field, clean athletic lane markings.',
      'A swimmer under water, sunlight creating golden patterns on the bottom of the blue pool.',
      'A fitness meal prep flat lay: grilled chicken, broccoli, sweet potatoes, and protein shaker on clean background.'
    ],
    videos: [
      'Slow motion shot of an athlete lifting a heavy barbell, determination on face, sweat dripping, cinematic gym lighting.',
      'Drone tracking shot running next to a female sprinter on an outdoor track, fast dynamic movement.',
      'Time-lapse of people working out in a modern CrossFit gym, high energy, fast-paced action.',
      'A boxer hitting a heavy bag in slow motion, dust and sweat particles flying from the impact, dark moody ring setting.',
      'Close-up of a person taking a refreshing drink of water from a shaker bottle after a workout, water droplets on skin.',
      'Slow motion of battle ropes creating waves in a dark gym, sweat drops flying, intense training.',
      'Drone tracking shot of a cyclist racing down a winding mountain pass road, high speed motion.',
      'Slow motion of a swimmer\'s arm breaking the water surface during freestyle stroke, water droplets.',
      'Time-lapse of people spinning on stationary bikes in a modern fitness studio, dynamic neon lights.',
      'A boxer punching a speed bag in slow motion, incredible hand speed and muscle focus.',
      'Slow motion of chalk dust flying as an athlete claps hands before lifting a heavy barbell.',
      'Camera moving alongside a runner sprinting along a scenic river path during sunrise.',
      'Slow motion first-person view running on a athletic track, looking at the red lane ahead.',
      'A female athlete performing pull-ups in slow motion, focused facial expression, back muscles tensed.',
      'Drone shot flying over outdoor yoga practitioners stretching on a wooden deck by a quiet lake.',
      'A climber reaching a cliff ledge in slow motion, secure grip on the rock, dusty chalk.',
      'Time-lapse of gym weights being organized and loaded on racks by trainers.',
      'Slow motion of a basketball swooshing through a net hoop, clean shot, sunset background.',
      'A female athlete doing sit-ups on a mat, camera tracking her dynamic movement, bright gym.',
      'Slow motion of a heavy kettlebell swing, camera following the weight rising and falling.',
      'A trainer adjusting the posture of an athlete during squats, professional coaching session.',
      'Slow motion of water being sprayed onto a runner\'s face, cooling droplets flying in high contrast.',
      'A dancer performing a beautiful leap in slow motion, fabric of clothes floating in the air.',
      'Camera tracking close to gym machinery pulleys moving rapidly during an intense workout.',
      'Slow motion of a female sprinter exploding from starting blocks, red track clay flying.',
      'A personal trainer smiling and high-fiving a client after a tough workout session.',
      'Slow motion of a gymnast landing a flip on a mat, perfect balance and relief.',
      'Camera panning across rows of clean modern dumbbells in a premium fitness club.',
      'Slow motion of a runner drinking from water bottle, water spilling down the neck, backlit sun flare.',
      'A high-energy time-lapse of a dance class practicing choreographies in a studio with mirror walls.'
    ]
  },
  {
    id: 'auto',
    name: 'Automotive & Autos',
    icon: '🏎️',
    description: 'Elegante Sportwagen, dynamische Roadtrips, glänzende Details.',
    previewImage: '/previews/auto.png',
    images: [
      'A sleek modern electric sports car driving on a scenic mountain highway at sunset, motion blur, gorgeous reflections, automotive photography.',
      'Close-up of a luxurious car headlight glowing at night in the rain, water droplets on the polished paint, glowing cyan neon lighting.',
      'A vintage red convertible parked on a coastal cliff path overlooking the ocean at sunset, nostalgic road trip aesthetic.',
      'Sleek modern car interior view at dusk, glowing digital dashboard, leather steering wheel, ambient LED lighting lines.',
      'A powerful off-road SUV kicking up dust while driving through a desert valley, high speed action freeze frame.',
      'A luxurious black sedan parked in a modern concrete garage, architectural spot lighting, clean minimalist design.',
      'A classic vintage sports car driving through a yellow autumn forest, colorful leaves flying behind it, motion blur.',
      'Close-up of a high-end chrome exhaust pipe emitting soft steam, red taillight glow, cold winter night.',
      'A powerful super car drifting on a wet race track at night, water spray glowing under bright stadium lights.',
      'Close-up of a designer car steering wheel with premium leather stitching, glowing logo, driver\'s hand.',
      'An electric SUV charging at a futuristic station at night, neon blue light lines, high-tech vibe.',
      'A red classic convertible parked on a coastal cliff road at sunset, endless ocean in background, travel vibe.',
      'Close-up of a mechanical engine bay, polished chrome and carbon fiber parts, clean high-performance engineering.',
      'A futuristic concept car with butterfly doors open, standing on a dark reflective studio floor, cyan lighting.',
      'Close-up of a tire tread driving through fresh snow, crisp white textures, winter road safety concept.',
      'A yellow sports car driving on a dusty desert highway, long sun rays casting dramatic shadows, high speed.',
      'An elegant car dashboard at night showing maps on a wide screen, soft interior ambient lighting in purple.',
      'Close-up of water droplets sliding off a freshly waxed car hood, glossy reflective paint, professional detailing.',
      'A group of friends on a road trip in a vintage off-road vehicle, driving along a sandy beach at sunset.',
      'Close-up of a luxury car key fob resting on a marble table next to a coffee cup, smart entry design.',
      'A professional mechanic working underneath a lifted car in a clean workshop, tools in hand, bright industrial light.',
      'A silver sedan driving fast through a modern city at night, neon lights creating long colorful reflection trails.',
      'Close-up of a carbon fiber side mirror reflecting a beautiful mountain road at sunset.',
      'A luxury camper truck parked in a snowy forest, warm yellow lights glowing from the window, adventure travel.',
      'Close-up of a gear shifter being moved into drive by a driver, polished aluminum, luxury car interior.',
      'A vintage motorcycle parked in front of a rustic brick wall, leather details, nostalgic custom bike aesthetic.',
      'Close-up of a car wheel rim spinning fast, high-quality alloy design, motion blur, clean asphalt.',
      'An SUV driving through a shallow muddy river in a green valley, water splashing everywhere, outdoor action.',
      'Close-up of a windshield with rain droplets, wipers in motion, blurred city neon lights in the background.',
      'A luxury car delivery showroom with a car covered in a red silk sheet, ready to be revealed, dramatic spotlights.'
    ],
    videos: [
      'Cinematic tracking video following a luxury sports car accelerating through a city tunnel at night, neon lights reflecting on the body.',
      'Drone shot sweeping over a car driving along a winding coastal road during sunrise, ocean waves below.',
      'Close-up slow motion pan of water droplets sliding off a freshly waxed sports car during a wash.',
      'Time-lapse of car lights creating neon trails on a busy highway at night, urban dynamic energy.',
      'A close-up of a driver pushing the start/stop button of a luxury car, engine roaring to life (visual vibration).',
      'Slow motion of a luxury sports car accelerating from a complete stop, tires smoking on the asphalt.',
      'Drone tracking video of an off-road SUV driving through sand dunes in the desert during golden hour.',
      'Slow motion pan across the digital cockpit dashboard of a modern electric car turning on, glowing menus.',
      'Time-lapse of cars driving on a winding mountain road at night, headlights and taillights creating red and white trails.',
      'Close-up slow motion of a person cleaning a luxury car wheel with a brush and soapy foam.',
      'A sports car driving through a water puddle in slow motion, massive dramatic splash reflecting sunlight.',
      'Drone flying low over a highway as a convoy of luxury cars drives in perfect formation.',
      'Close-up of a custom car exhaust pipe emitting pops and flames in slow motion, dark garage setting.',
      'Camera tracking alongside a classic car driving through a misty pine forest road in autumn.',
      'Slow motion of butterfly doors opening on a supercar in a bright high-end showroom.',
      'A time-lapse of professional car wrapping, matte black film being applied to a silver car.',
      'Close-up of a driver shifting gears manually, quick hand movement, focused sport steering wheel.',
      'Slow motion of water being sprayed off a car hood with a high pressure washer, clean coating.',
      'A drone shot rising up from a parked red convertible to reveal a beautiful coastal highway at sunset.',
      'Close-up of a digital charging screen in an electric car showing charging progress with a green pulse.',
      'Slow motion of car headlights flashing at the camera in a dark rainy night, glowing lens flare.',
      'A camera panning across a vintage motorcycle engine, highlighting the mechanical chrome details.',
      'Drone shot tracking a camper van driving along a cliffside ocean road at dusk, lights glowing.',
      'Slow motion of a driver adjusting the rearview mirror, reflection of passenger smiling, road trip vibe.',
      'Time-lapse of traffic passing through a massive modern suspension bridge, city skyline background.',
      'Close-up of a tire spinning out on gravel in slow motion, tiny stones flying, high energy.',
      'A camera tracking shot from the passenger seat showing a scenic road winding ahead, sunny day.',
      'Slow motion of a car owner wiping the polished car body with a microfiber cloth, shine reflection.',
      'Drone shot diving down a forest road as a sports car passes below, speed and dynamic action.',
      'Close-up of a smart lock system unlocking a car door automatically as the owner approaches.'
    ]
  },
  {
    id: 'socialmedia',
    name: 'Social Media',
    icon: '📱',
    description: 'Auffällige Content-Creator-Szenen, Unboxings und ästhetische Vlogs.',
    previewImage: '/previews/socialmedia.png',
    images: [
      'A cozy desk setup of a content creator, neon purple ring light reflection in the window, high-end microphone, modern camera on a tripod, aesthetic workspace.',
      'Close-up of a hand holding a smartphone displaying an colorful lifestyle feed, beautiful warm coffee shop background, soft bokeh.',
      'A young woman smiling in front of a ring light, filming a video for social media, bright and clean aesthetic, professional lighting.',
      'Flat lay of aesthetic tech accessories: wireless keyboard, pastel headphones, a journal, and a cup of matcha latte on a marble desk.',
      'A vibrant outdoor street style portrait of a content creator holding a vintage camera, sunny day, colorful background.',
      'A young female creator smiling while recording a beauty vlog, ring light reflection in her eyes.',
      'A modern aesthetic home office setup with dual monitors, plants, neon light signs, cozy workspace.',
      'Close-up of hands unboxing a high-end designer box, crisp textured paper, elegant branding.',
      'A content creator holding a camera stabilizer, filming a cinematic sequence in a city street.',
      'Flat lay of trendy tech gear: colorful keyboard, headphones, smartphone, and notebook on white desk.',
      'A lifestyle blogger enjoying coffee at an outdoor café table, holding a phone, sunny summer vibes.',
      'Close-up of a ring light illuminating a smartphone screen showing a live video stream interface.',
      'An influencer taking a selfie with a colorful graffiti wall background, trendy street style fashion.',
      'A podcast studio setup with professional microphones, soundproofing panels, and glowing neon sign.',
      'Close-up of a hand editing video footage on a tablet screen using a stylus, timeline visible.',
      'A cozy bedroom setup for filming, fairy lights on walls, tripod, soft pastel linen.',
      'A chef filming cooking videos in a bright kitchen, camera on a high tripod looking down.',
      'An aesthetic flat lay of makeup products, brushes, and a mirror on a marble vanity desk.',
      'A group of creators reviewing video analytics on a laptop screen, smiling and high-fiving.',
      'Close-up of a creator\'s microphone with a fuzzy wind muff, outdoor forest recording setting.',
      'A fitness creator recording a home workout using a smartphone on a tripod, bright sunny living room.',
      'A flat lay of travel blogging items: passport, sunglasses, camera, and espresso cup on wood.',
      'Close-up of a hand tapping the publish button on a smartphone app screen, modern interface.',
      'A stream chat overlay showing reactions and emojis on a dark transparent monitor screen.',
      'A digital nomad working on a laptop at a beach bar, looking out over the ocean at sunset.',
      'An unboxing of a vintage game console, colorful packaging, nostalgic gamer room background.',
      'Close-up of neon sign on a wall reading "CREATOR SPACE", bright pink and warm orange lights.',
      'A fashion blogger holding shopping bags, posing in a high-end shopping street, sunny afternoon.',
      'Close-up of professional audio wave graphs moving on a recording software dashboard.',
      'A flat lay of organic skincare products, green leaves, and glass dropper bottles on linen fabric.'
    ],
    videos: [
      'Slow motion cinematic panning over an aesthetic gaming and streaming setup with pulsing RGB neon lights.',
      'Time-lapse of a creator setting up a studio lights, softbox, and a tripod in a cozy room.',
      'A close-up of hands typing dynamically on a mechanical keyboard with glowing keycaps in slow motion.',
      'Camera flying gently over an aesthetic desk with a smartphone, coffee cup, and notepad, warm morning sunlight.',
      'A slow motion shot of a creator unboxing a high-tech gadget, crisp details, wrapping paper tearing off.',
      'Slow motion of a creator unboxing a high-end tech device, crisp details of peel-off plastic.',
      'Time-lapse of an artist creating digital art on a tablet, drawing fast lines with a stylus.',
      'Slow motion panning across a vibrant stream setup with purple and blue RGB lights pulsing.',
      'Close-up of hands tying ribbon on a gift box, unboxing prep, cozy warm fireplace background.',
      'Time-lapse of video editing software timeline moving fast, cuts and color grading adjustments.',
      'A vlogger walking through a crowded street, holding a camera on a selfie stick and talking, smiling.',
      'Close-up slow motion of coffee being poured into an aesthetic cup, morning sunlight on desk.',
      'A streamer reacting with surprise and laughter to a game event, facecam view, neon backdrop.',
      'Slow motion of a creator adjusting a professional microphone, soft studio backlight.',
      'Time-lapse of setting up a podcast studio: microphones, headphones, and sound checks.',
      'A camera tracking shot behind a fashion blogger walking down a street, looking back and smiling.',
      'Close-up of a finger sliding through a video editing timeline on a tablet, slow precision.',
      'Slow motion of a beauty creator applying highlighter, sparkling makeup particles in light.',
      'A digital nomad typing on a laptop at a beach bar, warm sunset waves in the background.',
      'Time-lapse of comments and likes count increasing rapidly on a mock social media dashboard.',
      'A close-up of hands peeling a screen protector off a brand new smartphone, satisfying motion.',
      'Slow motion of colorful confetti being thrown at the camera, creator celebrating milestone.',
      'Camera panning across a cozy stream space setup, showing a mechanical keyboard and warm mug.',
      'A traveler recording a vlog in front of a famous monument, holding a camera gimbal, sunny day.',
      'Close-up of hands clicking a high-end camera lens onto the body, sharp locking sound implied.',
      'Slow motion of an artist spraying colorful paint onto a canvas, street art content creation.',
      'A tech reviewer turning on a futuristic device, screens flashing, reflection in eyes.',
      'Time-lapse of drawing an illustration on paper, pencil moving fast, artistic content.',
      'Close-up of a smartphone ring light clip being attached, showing warm and cold LED rings.',
      'Slow motion of a dancer executing a spin in a mirror studio, dynamic social media video.'
    ]
  },
  {
    id: 'nature',
    name: 'Natur & Landschaften',
    icon: '🏔️',
    description: 'Atemberaubende Landschaften, tosende Wasserfälle und Nebelwälder.',
    previewImage: '/previews/nature.png',
    images: [
      'A breathtaking mountain valley at sunrise, mist rising from a crystal-clear lake, golden sunbeams cutting through pine trees, photorealistic 8k.',
      'Close-up of a dew-covered green fern leaf in a dense redwood forest, soft morning light, deep rich green tones, macro photography.',
      'A dramatic rocky coastline with heavy ocean waves crashing against cliffs under a stormy purple sunset, long exposure.',
      'A majestic waterfall cascading down a steep mossy cliff into a turquoise pool, lush tropical jungle environment, bright daylight.',
      'A peaceful path winding through a beautiful pink cherry blossom forest in Japan, soft warm sun rays, dreamy atmosphere.',
      'A dense pine forest covered in morning fog, mystical atmosphere, tall trees disappearing in mist.',
      'A close-up of a macro snowflake resting on a pine needle, perfect crystal structure, cold blue light.',
      'A tranquil forest stream flowing through autumn woods, colorful red and gold leaves on wet rocks.',
      'A majestic deer standing in a misty clearing at sunrise, sunbeams piercing the forest background.',
      'Close-up of a glowing firefly on a blade of grass at dusk, warm ambient light, magical bokeh.',
      'A dramatic stormy sky over green rolling hills, dark clouds contrast with bright grass sunlit patches.',
      'A desert landscape under a clear starry night sky, giant cactus silhouettes, milky way visible.',
      'Close-up of crystal clear water droplets on a spider web, morning dew glistening under soft sun.',
      'A peaceful field of blooming lavender reaching the horizon, sunset sky with orange and pink clouds.',
      'A lone hiker standing on a high mountain ridge overlooking a massive green valley, sunny afternoon.',
      'A close-up of a vibrant autumn leaf showing detailed vein structures, backlit by warm golden sun.',
      'A beautiful coastal cliff with a natural stone arch, waves crashing against the rocks under blue sky.',
      'A misty mountain lake reflecting towering snow-covered peaks, quiet and peaceful morning atmosphere.',
      'A close-up of green moss growing on wet wood, tiny forest plants, macro view, soft focus.',
      'A dramatic volcano eruption at night, red hot lava flowing down the dark slopes under ash clouds.',
      'A sunlit wildflower meadow with blooming daisies and poppies, bees flying around, bright summer day.',
      'A beautiful ice cave inside a glacier, glowing blue ice walls, light shining through the entrance.',
      'Close-up of a drop of water falling from a green leaf, capturing the splash ripple on water below.',
      'A majestic eagle flying high above green mountains and valleys, wide cinematic aerial view.',
      'A quiet sandy pathway through coastal dunes, sea oats blowing in the wind, clear blue sky.',
      'Close-up of a rustic old tree bark texture, moss growing in cracks, ancient forest feel.',
      'A frozen waterfall in winter, giant blue icicles hanging from a cliff, snow covered pines around.',
      'A beautiful rainbow forming over a green tropical island valley after a soft warm rain shower.',
      'Close-up of details of colorful pebbles on a lake shore, clear water washing over them, sun reflection.',
      'A deep redwood forest with ancient giant trees, sunbeams filtering down to the lush fern floor.'
    ],
    videos: [
      'Slow drone flight over a dense pine forest covered in mist at sunrise, epic cinematic atmosphere.',
      'Time-lapse of the Northern Lights dancing across a starry night sky above a snow-capped wooden cabin.',
      'Slow motion close-up of crystal clear water flowing over smooth river stones in a mountain stream.',
      'A drone rising slowly from a rocky ocean cliff to reveal a vast sunset horizon with waves breaking below.',
      'Time-lapse of fog rolling over green rolling hills in a valley, sun breaking through clouds.',
      'Slow drone flight over a winding river in a green forest, sunrise light breaking through trees.',
      'Time-lapse of a foggy valley, mist rising and clearing to reveal a beautiful mountain village.',
      'Slow motion of water droplets falling from a green leaf, macro lens tracking the drop splash.',
      'Time-lapse of clouds passing rapidly over snow-covered mountain peaks during a golden sunset.',
      'Slow motion of a waterfall cascading into a crystal clear pool, camera tracking the flow.',
      'A drone shot rising up from a dense autumn forest, showing vibrant orange and red colors.',
      'Slow motion close-up of a bee collecting pollen from a colorful flower, sunny summer garden.',
      'Time-lapse of stars and the Milky Way rotating over a lone tree in a wide field.',
      'Slow motion of ocean waves crashing against dark rocks on a stormy coast, sea foam.',
      'Drone shot tracking along a quiet sandy pathway leading to a beach through dunes.',
      'Slow motion of wind blowing through a field of wildflowers, daisies swaying under sunlight.',
      'A close-up of a stream of water flowing rapidly over frozen ice structures in winter.',
      'Drone shot flying low under the canopy of ancient giant redwood trees, sun rays.',
      'Slow motion of autumn leaves falling in a quiet forest, camera tracking their floating path.',
      'Time-lapse of ice melting on a lake shore, revealing colorful pebbles underneath.',
      'Slow motion of mist spraying from a big wave hitting a cliff, rainbow forming in the spray.',
      'A drone flying slowly along a ridge of snow-capped mountains at sunrise, golden light.',
      'Close-up slow motion of rain droplets hitting a puddle, creating expanding water ripples.',
      'Time-lapse of morning dew drying on a green fern leaf as the sun warms the forest.',
      'Slow motion of a deer running through a misty forest clearing, graceful dynamic movement.',
      'Drone shot flying high above a deep green valley with a winding river, sunny day.',
      'Close-up of a firefly glowing on a branch at night, pulsing light in slow motion.',
      'Slow motion of wind blowing through pine tree needles, soft green forest backdrop.',
      'A camera panning slowly across a beautiful lavender field at dusk, sky glowing orange.',
      'Slow motion of a crystal clear spring bubbling up from sandy ground, clean pure water.'
    ]
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk & Sci-Fi',
    icon: '👾',
    description: 'Futuristische Megacitys, neonbeleuchtete Gassen und High-Tech-Elemente.',
    previewImage: '/previews/cyberpunk.png',
    images: [
      'A dark rainy street in a futuristic cyberpunk city, glowing pink and cyan neon signs reflecting in puddles, flying cars in the sky, 8k resolution.',
      'Close-up portrait of a futuristic cyborg woman with glowing blue light patterns on her face, neon background, cyberpunk aesthetic.',
      'A high-tech control room with multiple glowing holographic screens, clean white and blue lighting, sci-fi spaceship interior.',
      'An abandoned futuristic laboratory overgrown with bioluminescent plants, glowing moss on high-tech devices, mysterious vibe.',
      'A futuristic motorbike parked in a dark neon-lit alleyway, smoke rising from the ground, high-contrast dramatic lighting.',
      'A futuristic cybernetic helmet resting on a laboratory table, glowing orange HUD reflection, high tech.',
      'A dense high-tech futuristic city street with flying vehicle trails, towering neon advertisements.',
      'Close-up of a cyberpunk hacker\'s fingers typing on a glowing holographic keyboard, cyber space data.',
      'An industrial alleyway in a cyberpunk city, neon green cables hanging, steam rising, rain puddles.',
      'Close-up of a cybernetic eye implant glowing red, detailed metallic iris, high tech portrait.',
      'A high-speed monorail train passing between neon-lit skyscrapers, futuristic public transport.',
      'A cozy futuristic apartment room with a panoramic window showing a rainy cyberpunk city skyline.',
      'Close-up of a robotic hand holding a glowing blue datapad, carbon fiber joints, dark tech background.',
      'A futuristic underground black market street, glowing signs, cyberwares, shady characters.',
      'Close-up of cybernetic wires connecting to a human neck port, glowing data transfers, sci-fi.',
      'A massive futuristic starship hangar bay with drones flying, industrial yellow crane lights.',
      'A cyberpunk street vendor cooking food under glowing red neon signs, steam rising from the wok.',
      'Close-up of a high-tech processor chip glowing with pulsing orange LED lines, computer motherboard.',
      'A futuristic laboratory with a glowing blue stasis capsule containing a mysterious humanoid figure.',
      'A cyberpunk mercenary standing on a rooftop in the rain, looking down at a glowing neon metropolis.',
      'Close-up of a holographic phone call projection floating above a hand, blue digital character.',
      'A sleek white sci-fi corridor with glowing curved light panels, minimalist clean future design.',
      'Close-up of a neon-lit cyberpunk style helmet visor reflecting glowing city streets, dark alley.',
      'A futuristic greenhouse on Mars with hydroponic plants growing under glowing pink UV lights.',
      'Close-up of a futuristic gun with glowing status indicators, resting on a steel metallic surface.',
      'A futuristic cyber bar interior, glowing tables, holographic drink menus, cyborg bartender.',
      'Close-up of a digital wristwatch displaying cyberware status, glowing green futuristic HUD.',
      'A sci-fi research outpost on a cold icy planet, glowing dome structures under starry purple sky.',
      'Close-up of a cybernetic arm joint moving, polished metallic plate showing hydraulic pistons.',
      'A futuristic solar panel farm in a desert under giant glowing dust storms, dark sci-fi mood.'
    ],
    videos: [
      'Cinematic fly-through of a massive futuristic metropolis at night, glowing neon towers and flying vehicles.',
      'Slow motion pan across a high-tech sci-fi server room with pulsing blue and green led status lights.',
      'A glowing hologram displaying a rotating planet earth in a dark command center, futuristic interface in motion.',
      'Camera moving through a rainy neon-lit alleyway in a futuristic city, steam escaping from pipes.',
      'A spaceship slowly descending onto a futuristic landing pad on a foreign planet at dusk.',
      'Slow motion of rain falling in a cyberpunk alleyway, neon signs reflecting in ripples of a puddle.',
      'Drone shot flying between towering neon-lit skyscrapers in a massive futuristic cyberpunk city.',
      'Time-lapse of a glowing holographic planet rotating in a dark command center, interfaces shifting.',
      'Slow motion pan across high-tech sci-fi server racks with pulsing green status LED lights.',
      'A spaceship slowly descending onto a landing pad of a futuristic neon city at dusk.',
      'Time-lapse of neon advertisements flashing on the facade of a massive futuristic metropolis building.',
      'Slow motion of cybernetic fingers typing on a keyboard, metallic joints reflecting neon glow.',
      'Drone shot tracking a high-speed monorail train gliding through a futuristic neon city.',
      'Slow motion zoom on a cyborg\'s face as a cybernetic eye implant blinks and recalibrates with red HUD.',
      'Camera moving through a futuristic white laboratory corridor, glass panels showing research setups.',
      'Slow motion of steam rising from a cyberpunk street food vendor\'s grill, neon lights glowing.',
      'Time-lapse of data charts scrolling on holographic displays in a high-tech control room.',
      'A drone diving down a dark rainy skyscraper canyon, flying cars passing by with neon light trails.',
      'Slow motion of a holographic projection loading, blue light particles forming a humanoid avatar.',
      'Close-up of a smart lock system displaying a glowing green "ACCESS GRANTED" status screen.',
      'Slow motion of cybernetic wires being plugged into a computer port, sparks flying on impact.',
      'A camera panning across a futuristic Mars greenhouse, showing green leaves under pink lights.',
      'Drone shot tracking a futuristic bike driving fast on a wet highway at night, neon light trails.',
      'Slow motion of water dripping from neon cables in a dark cyberpunk street alleyway.',
      'Time-lapse of stars moving behind a sci-fi dome research station on a snow planet.',
      'A close-up of a robotic arm sorting processor chips in a futuristic automated factory.',
      'Slow motion pan of a cyberpunk bar lounge, glowing cocktails, silhouettes of people talking.',
      'Drone shot rising from a massive industrial ventilation fan spinning in a futuristic city wall.',
      'Slow motion of a cybernetic helmet visor being closed, showing boot-up diagnostics screens.',
      'A time-lapse of a massive solar panel field adjusting angles under a glowing green alien sky.'
    ]
  },
  {
    id: 'artistic',
    name: 'Kunst & Abstrakt',
    icon: '🎨',
    description: 'Farbexplosionen, flüssige Strukturen und surreale Traumlandschaften.',
    previewImage: '/previews/artistic.png',
    images: [
      'An abstract macro shot of swirling colorful acrylic paints in water, vibrant pink, gold, and deep blue patterns, artistic fluid art.',
      'A surreal dream landscape with floating geometric shapes, a glowing portal in the center, pastel clouds, fantasy concept art.',
      'An artistic double exposure portrait of a woman merged with a lush green forest, sun rays filtering through leaves, emotional.',
      'Vibrant splashing paint frozen in mid-air, dynamic colorful liquid droplets on a dark reflective background, commercial studio lighting.',
      'A minimalist modern sculpture standing in a bright gallery room, shadows cast on a clean concrete wall, artistic gallery style.',
      'An abstract composition of floating gold geometric rings and spheres on a white minimalist background.',
      'A close-up of colorful smoke patterns swirling in a dark space, vibrant pink and cyan hues.',
      'An artistic double exposure of a man\'s silhouette filled with a busy night city highway light trails.',
      'A surreal landscape with giant glowing mushrooms, a river of liquid silver under a purple moon.',
      'Close-up of a paintbrush creating thick textured oil strokes on a canvas, vibrant color mixing.',
      'Abstract architectural structures with sharp angles and dramatic shadows, clean concrete and blue sky.',
      'A surreal portrait of a woman whose hair transitions into splashing waves of turquoise ocean water.',
      'Close-up of liquid gold splashing against a black surface, dynamic metallic droplet shapes.',
      'An abstract digital sculpture made of glowing neon light lines, floating in a dark mirror room.',
      'Close-up of dried paint cracks on an old wooden surface, abstract natural textures and colors.',
      'A surreal scene with a vintage piano standing on a deserted beach, waves gently washing over keys.',
      'An abstract macro shot of soap bubble patterns reflecting iridescent rainbow colors, close-up.',
      'A minimalist plaster art canvas on a wall, textured white waves, warm sunlight casting shadows.',
      'An artistic portrait of a dancer captured in motion, soft camera zoom causing beautiful motion blur.',
      'A surreal sky filled with multiple glowing moons, pastel colored clouds, fantasy dream environment.',
      'Close-up of colorful ink dissolving in water, macro shot showing organic cell-like structures.',
      'An abstract wallpaper design with fluid lines of gold, turquoise, and deep navy blue paint.',
      'Close-up of metallic liquid mercury drops rolling on a black surface, high reflective textures.',
      'A surreal bedroom where the floor is a calm water pond with swimming orange koi fish.',
      'Close-up of stained glass patterns reflecting colorful warm light beams on a stone floor.',
      'An abstract dynamic sculpture made of rusted metal sheets and bright green neon tubes.',
      'Close-up of oil and water mixtures, colorful circle bubbles reflecting iridescent light.',
      'A surreal staircase climbing up into a sky full of stars and floating books, fantasy dream.',
      'Close-up of an artist\'s palette showing textured mixtures of acrylic paints, messy creative look.',
      'A beautiful flat lay of abstract ceramic shapes, dried flowers, and terracotta vases on linen.'
    ],
    videos: [
      'Slow motion close-up of colorful ink droplets expanding and mixing in water, creating beautiful fluid clouds.',
      'A surreal camera flight through an abstract landscape of geometric gold shapes and floating marble spheres.',
      'Time-lapse of an artist creating a vibrant abstract painting on a large canvas, energetic brush strokes.',
      'A beautiful slow-motion splash of liquid gold against a black background, high contrast lighting.',
      'Slow pan across an abstract digital wave structure glowing with warm orange and violet colors.',
      'Slow motion of colorful paint splashing and mixing in mid-air, dark reflective background.',
      'A camera panning slowly across a modern gallery room, showing abstract large canvas paintings.',
      'Slow motion of liquid gold flowing over a black marble surface, creating shiny metallic veins.',
      'Time-lapse of an artist creating a detailed charcoal portrait, rapid hand movements.',
      'Slow pan across abstract digital waves glowing with warm orange and violet color gradients.',
      'A surreal video of a door opening in a green field to reveal a starry night space.',
      'Slow motion of iridescent soap bubbles floating, light creating shifting rainbow colors.',
      'Time-lapse of oil paints blending slowly on a canvas, creating natural abstract patterns.',
      'A camera tracking through a surreal landscape of floating giant marble spheres and golden pillars.',
      'Slow motion of colorful ink droplets expanding in water, creating beautiful cloud formations.',
      'A digital simulation of colorful sand structures shifting and morphing in slow motion.',
      'Slow motion of water dropping onto liquid mercury, creating perfect metallic ripple waves.',
      'A drone shot rising from a grand white sculpture in a modern museum garden, sunny day.',
      'Slow motion of a dancer spinning with a long silk fabric trailing and floating in the air.',
      'Time-lapse of light changing shadows cast by a geometric modern structure onto concrete.',
      'Slow motion of colorful smoke rings being blown against a dark backlighting, high detail.',
      'A camera tracking shot moving alongside a river of liquid silver flowing through dark sand.',
      'Slow motion of an artist dropping watercolors onto wet paper, color bleeding organically.',
      'A surreal landscape zoom, flying through a glowing triangular portal in pastel clouds.',
      'Close-up slow motion of clay being shaped on a potter\'s wheel, wet hands smoothing contours.',
      'Time-lapse of colorful crystals growing under a microscope, abstract geometric patterns.',
      'Slow motion of paint droplets bouncing on a speaker cone vibrating with heavy music bass.',
      'Drone shot flying high above a field of giant colorful geometric crop circles, sunny day.',
      'Slow motion of liquid glass being blown and shaped into a vase by an artisan, glowing red.',
      'A camera rotating around a glowing neon tube sculpture, reflecting in wet dark floor panels.'
    ]
  }
];
