export const PROMPT_CATEGORIES = [
  {
    id: 'winzer',
    name: 'Winzer & Weinberge',
    icon: '🍇',
    description: 'Edle Tropfen, Weinkeller, sonnige Weinreben und traditionelle Ernte.',
    images: [
      'A sun-drenched vineyard in Tuscany during autumn harvest, golden hour light glowing through ripe purple grapes, morning dew on leaves, cinematic lighting, photorealistic, 8k resolution.',
      'An elderly winemaker with weathered hands holding a glass of deep red wine against a rustic wooden barrel background, warm ambient light, high detail portrait.',
      'Close-up shot of wine being poured into a crystal glass, dynamic splash, dark elegant background, backlit, commercial product photography.',
      'A modern, minimalist wine cellar with concrete walls, glowing warm LED lines highlighting rows of premium bottles, architectural digest style.',
      'A cozy outdoor wine tasting table on a hillside overlooking a misty valley at sunrise, rustic wooden table, two glasses, a bottle, fresh cheese plate.',
      'Close-up of a single green grape bunch on a vine, macro photography, water droplets refracting sunlight, soft bokeh background.',
      'Winemaker inspecting a soil sample in a vineyard, low angle shot, sunrise, lens flare, professional agricultural photography.',
      'An ancient stone wine cellar filled with dusty vintage bottles and oak barrels, soft candlelight, mysterious and historical atmosphere.',
      'A group of friends laughing and cheering with white wine glasses in a lush green vineyard patio during a summer evening sunset, lifestyle photography.',
      'Artistic flat lay of wine bottles, corkscrew, green leaves, grapes, and dried figs on a textured dark slate surface, moody styling.',
      'A professional wine tasting room, clean bright light, white tables with neat rows of tasting glasses, professional sommelier setting.',
      'Harvest season, hands of workers carefully cutting grape bunches from the vine, warm afternoon sun, authentic documentary style.',
      'A stylized, artistic shot of red wine swirling inside a large glass, creating beautiful leg patterns, dark studio setting, dramatic lighting.',
      'A beautiful modern vineyard estate house surrounded by rolling hills, cinematic wide shot, clean blue sky, luxury travel vibe.',
      'A vintage tractor parked between rows of green vines under a dramatic cloudy sunset sky, rustic country aesthetic.',
      'A close-up of a wine cork being pulled out of a bottle, wood texture background, dynamic action freeze frame.',
      'An organic bio-vineyard with wildflowers blooming between the rows, bees flying around, bright sunny day, vibrant colors.',
      'A sommelier in a high-end restaurant decanting red wine, elegant movement, soft dark background, focused lighting on the flow of liquid.',
      'A romantic couple walking hand-in-hand through vineyard paths during golden hour, sun flare, emotional and warm atmosphere.',
      'A bottle of rosé wine chilling in a silver bucket filled with ice cubes, condensation on the bottle, bright summer pool deck background.'
    ],
    videos: [
      'Slow motion drone flyover above rolling green vineyard hills at sunrise, mist rising from the valley, cinematic golden light.',
      'Close-up slow motion of red wine pouring into a glass, rich texture, beautiful reflections, 240fps, studio light.',
      'Camera moving through a dark, historic wine cellar, passing wooden barrels illuminated by warm flickering candlelight.',
      'A winemaker gently rotating a wine bottle in a rack, checking the sediment, soft focused lighting, professional motion.',
      'Time-lapse of clouds passing over a beautiful vineyard valley during sunset, colors changing from orange to deep purple.',
      'Close-up of hands picking ripe grapes from the vine, placing them in a wooden basket, warm sunlight filtering through leaves.',
      'Extreme close-up macro shot of dew melting on a grape bunch under the morning sun, glistening water droplets.',
      'A group of people clinking wine glasses in slow motion, laughter, warm ambient lighting, festive outdoor dinner party.',
      'A drone rising up from a single grapevine to reveal a massive, beautiful estate during autumn, vibrant orange and red leaves.',
      'Red wine swirling inside a glass, camera tracking the liquid motion in slow-motion, dark high-contrast background.',
      'Winemaker walking down a row of vines, running his hand gently over the leaves, morning sun behind him, lens flare.',
      'A bottle of sparkling wine being popped open, cork flying, champagne spraying in slow motion, black background, high energy.',
      'Macro shot of wine fermenting in a steel tank, bubbles slowly rising to the surface, industrial winemaking process.',
      'Pouring white wine into a glass on an outdoor table, vineyard view in the blurred background, soft breeze blowing leaves.',
      'Close-up of a wine bottle label being designed or printed, modern high-tech printing press in motion.',
      'Camera panning across a luxury wine tasting table with cheese, grapes, crackers, and multiple glasses of red and white wine.',
      'Workers loading crates of freshly harvested grapes onto a rustic truck, afternoon sun, busy energetic atmosphere.',
      'A wine glass standing on a stone wall in the wind, vineyard landscape stretching into the horizon, calm serene mood.',
      'Detailed shot of a corkscrew twisting into a wooden cork, pulling it out slowly, sound-evoking visual.',
      'Slow motion splash of white wine dropping onto a fresh grape on a reflective black surface, commercial style.'
    ]
  },
  {
    id: 'immo',
    name: 'Immobilienmakler',
    icon: '🏠',
    description: 'Moderne Luxusvillen, gemütliche Innenräume und verkaufsstarke Details.',
    images: [
      'Luxury modern villa with glass walls, glowing pool in the foreground, twilight sky, architectural photography, ultra-premium lifestyle.',
      'Bright and airy Scandinavian-style living room, large windows, minimalist furniture, plants, sunny afternoon light, interior design magazine style.',
      'An elegant real estate agent shaking hands with a happy young couple in front of a modern suburban home, warm and welcoming look.',
      'Aerial drone view of a prestigious coastal neighborhood, blue ocean, luxury yachts, sunny day, clean aesthetic.',
      'A cozy farmhouse kitchen with rustic wooden beams, modern copper appliances, warm light, inviting home feel.',
      'Minimalist loft apartment with exposed brick walls, high ceilings, large industrial windows, afternoon light beams.',
      'Close-up of a stylized silver key with a house-shaped keychain resting on a polished wooden table, soft focus background.',
      'A chic modern office space inside a penthouse, panoramic city view through floor-to-ceiling windows at dusk.',
      'An upscale backyard patio with a fire pit, comfortable outdoor sofas, string lights glowing, warm evening vibe.',
      'A real estate agent presenting a house layout on a digital tablet to clients in a bright office, professional and modern.',
      'Beautiful curb appeal of a classic Victorian house, manicured green lawn, blooming flowers, bright sunny day.',
      'Luxurious master bathroom with a freestanding tub, marble walls, gold fixtures, soft spa-like lighting.',
      'A massive walk-in closet in a luxury home, boutique-style lighting, neatly organized designer clothes and shoes.',
      'Modern tiny house in a beautiful forest setting, large glass front, warm lights inside, peaceful nature vibe.',
      'A clean, professional headshot of a real estate agent, confident smile, blurred modern office interior background.',
      'A spacious empty room with light hardwood floors, sunbeams casting shadows on the walls, fresh start feel.',
      'An elegant dining table set for a family dinner in a luxury home, glowing chandelier, warm atmosphere.',
      'A stylish home theater room, plush reclining seats, ambient blue LED lighting, large screen.',
      'A sleek apartment entrance with a smart lock, modern security panel, minimalist design.',
      'Aerial view of a modern green eco-friendly housing development with solar panels and parks, clean future living.'
    ],
    videos: [
      'Smooth cinematic walk-through video entering a luxury villa through double front doors, revealing a massive open-space living room.',
      'Drone flying slowly towards a cliffside mansion at sunset, highlighting the infinity pool and ocean view.',
      'Slow pan across a ultra-modern kitchen, showing high-end appliances, marble countertops, and sunbeams.',
      'A real estate agent turning a key in a lock, opening a modern front door, and gesturing to come inside with a smile.',
      'Time-lapse of natural light moving across a beautifully decorated minimalist living room from morning to evening.',
      'Drone shot rising up from a backyard swimming pool to show a beautiful two-story suburban family home.',
      'A happy family running into their new empty living room, children jumping with joy, emotional lifestyle scene.',
      'Close-up panning shot of luxury bathroom details: water running into a marble tub, soft steam rising.',
      'Cinematic slider shot of a modern home office with a city view, transition from daylight to glowing city lights.',
      'Close-up of a pen signing a housing contract, contract paper, hand movement, professional and decisive.',
      'Slow motion of a couple clinking champagne glasses inside their newly bought modern apartment.',
      'Camera floating through a cozy bedroom with soft linens, curtains gently swaying in a light breeze.',
      'Drone view tracing a long driveway leading up to a grand estate house surrounded by autumn trees.',
      'Interactive 3D-like camera rotation around a sleek kitchen island with fresh flowers and breakfast setup.',
      'A real estate sign in the front yard transitioning from "For Sale" to "SOLD" with a stamp effect.',
      'Camera descending from a high wooden ceiling down to a modern fireplace crackling with warm fire.',
      'A drone shot sweeping over a neighborhood park, showing kids playing and nearby modern family homes.',
      'Slow pan of a smart home interface on a wall screen being touched to dim the living room lights.',
      'A virtual tour style walk-through of a luxury penthouse balcony overlooking a glowing city skyline at night.',
      'Close-up of a house key being placed into a client\'s hand, hand closing gently, emotional moment.'
    ]
  },
  {
    id: 'hochzeit',
    name: 'Hochzeit',
    icon: '💍',
    description: 'Romantische Paare, Hochzeitsdeko und emotionale Freudentränen.',
    images: [
      'A romantic bride and groom embracing under a floral arch at sunset, soft golden backlighting, wind blowing veil, emotional fine art photography.',
      'Close-up of wedding rings resting on a delicate white rose petal with tiny dew drops, macro shot, soft pastel bokeh background.',
      'An elegant outdoor wedding reception under fairy lights at night, long wooden tables filled with flowers and candles, magical atmosphere.',
      'The bride getting ready, mirror reflection showing her mother adjusting the wedding dress veil, emotional black and white portrait.',
      'A multi-tiered white wedding cake decorated with fresh pastel flowers and gold leaf details, standing on a rustic wooden table.',
      'The groom looking at the bride walking down the aisle, emotional expression, teary eyes, soft focused background.',
      'An aerial drone shot of a wedding ceremony on a white sandy beach, turquoise water, wooden altar with white drapery.',
      'A bride’s hands holding a lush bouquet of eucalyptus, white peonies, and dusty roses, detailed shot, elegant dress texture.',
      'First dance of a newlywed couple in a grand ballroom, sparkling light reflections, smoke effect on the floor, romantic mood.',
      'A vintage wedding getaway car, classic convertible decorated with flowers and a "Just Married" sign, driving down a scenic road.',
      'Bride and groom walking through a field of lavender at sunset, dreamy pastel colors, cinematic wide shot.',
      'Close-up of a champagne toast, many glasses clinking together, bubbles rising, happy blurred faces in the background.',
      'A beautiful wedding invitation suite laid out on a silk fabric, calligraphy, wax seal, green leaves, flat lay.',
      'Bridal party laughing and tossing flower petals in the air, joyful energy, bright sunny outdoor setting.',
      'A groom adjusting his bow tie in front of a window, soft natural light, focused and sharp portrait.',
      'A dramatic silhouette of a bride and groom kissing inside an ancient church doorway, light beaming in from behind.',
      'An intimate wedding ceremony in a redwood forest, tall trees, sunbeams filtering through leaves, natural rustic setup.',
      'Close-up of the bride\'s shoes and wedding dress lace details resting on a luxurious velvet chair.',
      'A flower girl throwing rose petals down the aisle, cute expression, bright sunlight, soft focus.',
      'A sparkling sparkler exit, guests holding sparklers creating a tunnel for the laughing bride and groom running through.'
    ],
    videos: [
      'Slow motion of the bride’s veil catching the wind at sunset, golden light illuminating the fabric, romantic camera rotation.',
      'Drone shot flying over a beautiful wedding ceremony setup on a cliff overlooking the ocean during golden hour.',
      'The groom’s emotional reaction as the camera pans to show the bride walking down the aisle in slow motion.',
      'Close-up slow-motion of a champagne cork popping, sparkling wine pouring out, guests cheering in the background.',
      'Slow motion first dance, the groom spinning the bride, her dress swirling, soft fairy lights bokeh in the background.',
      'A camera tracking shot behind the bride and groom as they walk hand-in-hand through a cheering crowd throwing white rose petals.',
      'Macro shot of wedding rings glistening in the sun, slowly rotating on a mirror surface.',
      'Time-lapse of a wedding reception venue being decorated, from empty hall to a magical candlelit dinner setting.',
      'The bride laughing with her bridesmaids as they toast with champagne glasses while wearing matching silk robes.',
      'A romantic slow pan of the wedding table setup, showing flickering candles, elegant plates, and fresh flowers.',
      'Drone shot tracking a classic vintage car driving along a coastal road at sunset with a "Just Married" sign shaking.',
      'Close-up of the bride and groom\'s hands joining together during the vows, soft micro-movements, emotional focus.',
      'A sparkler exit in slow motion, sparks flying, the couple kissing in the middle of the glowing path.',
      'The couple walking through a forest path, sun rays breaking through the trees, camera moving smoothly ahead of them.',
      'Slow motion slice being cut from a beautiful wedding cake, revealing the delicious layers inside.',
      'The bride\'s father wiping a tear from his eye during the wedding speech, authentic emotional documentary style.',
      'Camera panning up from the groom’s polished shoes to his nervous but happy smile in front of the mirror.',
      'A beautiful outdoor altar with white curtains blowing gently in the sea breeze, empty before the ceremony.',
      'Slow motion of the bouquet toss, group of excited women reaching for the flowers in the air.',
      'Romantic kiss under a tree decorated with hundreds of hanging glowing lanterns at night.'
    ]
  },
  {
    id: 'strand',
    name: 'Strandmotive',
    icon: '🏖️',
    description: 'Feiner Sand, türkisfarbenes Wasser, Wellenrauschen und Palmen.',
    images: [
      'A pristine tropical beach with crystal clear turquoise water, white sand, coconut palm trees leaning over the sea, sunny paradise vibe, 8k.',
      'A dramatic sunset over a stormy ocean, dark purple clouds, glowing orange horizon, waves crashing on black volcanic sand.',
      'Close-up of a beautiful seashell half-buried in wet sand, a gentle wave washing over it, macro shot, morning sunlight.',
      'A lone hammock tied between two palm trees on a secluded island beach, overlooking a calm blue lagoon, relaxing mood.',
      'An aerial drone shot of footprints leading into the ocean on a golden beach, perfect symmetry, minimal aesthetic.',
      'A rustic beach bonfire at twilight, sparks flying into the starry sky, cozy blankets and surfboards nearby.',
      'A tropical cocktail in a coconut with a straw, resting on a beach towel, sunny ocean background, refreshing summer vibe.',
      'A surfer carrying a surfboard walking towards massive waves at sunrise, mist on the water, high contrast silhouette.',
      'A wooden pier stretching far into a calm pastel-colored ocean at dawn, pink and purple sky, serene landscape.',
      'A tidal pool filled with colorful starfish and sea anemones on a rocky coast, clear water, bright day.',
      'A luxury beach villa patio with comfortable loungers, open to a private white sand beach and calm sea.',
      'A close-up of dynamic ocean waves breaking, capturing the transparent blue-green tube of water, sunlight shining through.',
      'A romantic picnic setup on the beach at sunset, low wooden table, cushions, wine, candles, warm ocean breeze.',
      'A flock of seagulls flying low over a sandy beach during a bright windy afternoon, dynamic motion.',
      'A child building a sandcastle on the shore, warm sunlight, soft bokeh of waves in the background.',
      'An exotic black sand beach in Iceland, dramatic basalt columns, white sea foam crashing, moody atmospheric look.',
      'A classic beach cruiser bicycle parked in the sand dunes with sea oats blowing in the wind, sunny retro vibe.',
      'Close-up of feet stepping into warm sandy beach water, ripples in the water, relaxing summer feel.',
      'A majestic sea turtle swimming over a vibrant coral reef near a sunny beach shore, underwater split-shot.',
      'A lighthouse standing tall on a grassy cliff overlooking a vast ocean under a clear blue sky.'
    ],
    videos: [
      'Cinematic drone shot flying low over the shoreline, crystal clear waves gently rolling onto pristine white sand.',
      'Time-lapse of a breathtaking tropical sunset, sky transitioning from yellow to deep pink, sun dipping below the ocean horizon.',
      'Close-up slow-motion of a wave breaking, capturing the crystal-clear water tube and white foam splashing.',
      'Camera moving forward underneath palm leaves swaying in a tropical breeze, revealing a beautiful sunny beach.',
      'A cozy beach bonfire burning at night, sparks drifting up, sound of crashing waves implied visually.',
      'Aerial top-down view of turquoise water clashing with white sand, creating beautiful natural patterns.',
      'A surfer paddling out into the ocean during a golden sunrise, misty water surface, epic scale.',
      'Slow pan across a romantic beach picnic setup at dusk, candles flickering, waves in the background.',
      'Footprints in the wet sand being slowly washed away by a gentle incoming wave in slow motion.',
      'Underwater camera swimming alongside colorful tropical fish and a sea turtle near a sandy shore.',
      'Time-lapse of tide pools filling up with ocean water as the tide comes in over dark coastal rocks.',
      'Camera tracking a person walking along the beach at sunrise, holding sandals in hand, peaceful morning walk.',
      'A luxury beach resort infinity pool blending seamlessly with the ocean at twilight, lights turning on.',
      'A storm approaching the beach, dark heavy clouds, strong wind blowing sand dunes, dramatic energy.',
      'Close-up of a cold tropical drink sweating with condensation, sun shining through the glass, beach background.',
      'Slow motion of colorful kites flying high above a crowded, sunny summer beach.',
      'A drone rising up from a historic lighthouse to reveal a massive rocky coastline and crashing waves.',
      'A hammock gently swaying between two palms as the sun sets in the background, creating a silhouette.',
      'Crabs running across wet sand, ducking into small holes as a wave approaches, macro tracking shot.',
      'Gentle mist spraying from a big wave hitting a cliff, rainbow forming in the mist under the sun.'
    ]
  },
  {
    id: 'urlaub',
    name: 'Urlaubsmotive',
    icon: '✈️',
    description: 'Roadtrips, fremde Kulturen und weltberühmte Aussichtspunkte.',
    images: [
      'A traveler standing on the edge of a cliff in Norway, looking at a massive fjord below, epic scale, sunny day, adventure travel.',
      'A cozy wooden cabin in the Swiss Alps covered in snow, warm lights glowing inside, smoking chimney, starry winter night.',
      'A classic Vespa scooter parked in a narrow, flower-filled street in Santorini, white houses, blue domes, bright sunny day.',
      'An infinity pool overlooking the jungle in Bali at sunrise, mist rising from the trees, luxury resort vibe.',
      'A hot air balloon flight over Cappadocia at dawn, hundreds of balloons in the sky, unique rocky landscape.',
      'A traditional wooden boat floating on a crystal clear lake in the Dolomites, surrounded by towering mountain peaks.',
      'A bustling colorful market street in Marrakech, spices stacked in cones, lanterns glowing, rich textures.',
      'A traveler reading a book on a balcony overlooking the Eiffel Tower in Paris, morning coffee and croissants on the table.',
      'An old train winding through lush green tea plantations in Sri Lanka, mist, vintage travel aesthetic.',
      'A luxury glamping tent in the middle of the desert under a clear Milky Way galaxy sky, glowing campfire.',
      'A highway stretching through the red rock desert of Route 66, USA, road trip vibe, endless horizon.',
      'A close-up of a passport with stamps and boarding passes resting on a wooden vintage suitcase, wanderlust concept.',
      'A couple kayaking in a glowing bio-luminescent bay at night, magical blue water glowing under their paddles.',
      'A quiet canal in Venice in the morning, gondola parked by historic stone walls, soft reflection in the water.',
      'A surfer overlooking a lush green coastline and breaking waves in Hawaii, tropical adventure vibe.',
      'A beautiful traditional ryokan room in Kyoto, open sliding doors showing a zen garden with autumn maple leaves.',
      'A modern camper van parked on a cliff overlooking the ocean at sunset, bonfire burning next to it, vanlife.',
      'A hike through a bamboo forest in Japan, sunbeams filtering through the tall green stalks, serene nature shot.',
      'An epic wide shot of the Taj Mahal at sunrise, pink mist over the reflecting pool, majestic travel icon.',
      'A traveler swimming in a hidden cenote cave in Mexico, sunbeam shining through a hole in the ceiling onto the blue water.'
    ],
    videos: [
      'Cinematic drone flyover of a hot air balloon rising over the unique rock formations of Cappadocia at sunrise.',
      'First-person view walking through a narrow, colorful street in an Italian coastal village, locals waving, sunny day.',
      'Slow motion of a train window view passing through lush green mountains and misty forests in Asia.',
      'Drone shot diving down a massive waterfall in Iceland, spray hitting the camera, epic adventure feel.',
      'A camper van driving along a winding coastal highway at sunset, camera tracking from behind.',
      'Time-lapse of the northern lights dancing over a cozy wooden cabin in a snowy forest in Lapland.',
      'Slow pan across a luxury resort balcony breakfast setup, revealing a panoramic view of the Amalfi coast.',
      'Underwater camera swimming into a deep blue cenote cave, light rays shifting in the water.',
      'A person jumping off a wooden pier into crystal clear tropical water, splashing in slow motion.',
      'Drone shot flying through a deep canyon in Utah, red rock walls towering on both sides.',
      'Time-lapse of stars moving across the sky above a tent in a sand dune desert, campfire glowing.',
      'First-person view kayaking through calm turquoise waters between massive limestone cliffs in Thailand.',
      'A camera tracking shot of a traveler walking through a bustling night market in Tokyo, neon lights reflecting.',
      'A traditional boat moving slowly through a misty lake in the mountains at dawn, water ripples.',
      'Slow motion of autumn leaves falling in a historic park in London, tourists walking in the background.',
      'A drone rising up from a swimming pool to show a luxury cliffside villa overlooking the Mediterranean sea.',
      'A hiker reaching the summit of a mountain, raising arms in triumph, wind blowing, panoramic view.',
      'Close-up of a map being unfolded on a car hood, fingers tracing a route, road trip preparation.',
      'A gondola gliding smoothly through a quiet Venice canal under a stone bridge, morning sun.',
      'Slow motion of waves hitting the wheels of a beach buggy driving on a sandy coast at sunset.'
    ]
  },
  {
    id: 'lostplaces',
    name: 'Lost Places',
    icon: '🏚️',
    description: 'Verfallene Säle, überwucherte Ruinen und mystischer Verfall.',
    images: [
      'An abandoned grand ballroom with a decaying crystal chandelier hanging from a cracked ceiling, dust motes dancing in sunbeams, eerie beauty.',
      'A rusted steam locomotive overgrown with green ivy and wildflowers inside a collapsed train depot, nature reclaiming technology.',
      'A forgotten library with decaying books scattered on the floor, moss growing on wooden bookshelves, light streaming through a broken stained-glass window.',
      'An empty amusement park at twilight, a rusted Ferris wheel silhouetted against a moody dark purple sky, overgrown weeds.',
      'An abandoned glass greenhouse, half-broken glass panels, overgrown tropical plants bursting out, soft misty atmosphere.',
      'A decaying retro diner from the 1950s, dust-covered jukebox, cracked leather booths, sun rays highlighting peeling paint.',
      'An empty theater stage with velvet curtains rotting away, a single spotlight beam of sunlight hitting an old wooden chair.',
      'An abandoned industrial factory floor, massive rusted pipes, broken machinery, moss carpet on the concrete floor, high contrast lighting.',
      'A forgotten mansion hallway with peeling wallpaper, cracked mirrors reflecting dust, a grand staircase covered in debris.',
      'An old classroom with a dusty blackboard still showing chalk writings from decades ago, small wooden desks, moody lighting.',
      'An abandoned shipwreck stranded on a rocky coast, rusted hull, waves crashing against it, dramatic overcast sky.',
      'A decaying vintage car parked inside an overgrown wooden barn, sunbeams piercing through gaps in the wood walls.',
      'An empty mental asylum ward, peeling paint on walls, rusted metal bed frame in the center, creepy atmospheric look.',
      'An abandoned stone cottage in a dense forest, roof collapsed, trees growing inside the living room, fantasy aesthetic.',
      'A forgotten underground subway station, rusted tracks, peeling posters from the 80s, eerie green emergency lighting.',
      'An old piano standing in the middle of a decaying church, dust layers on keys, light beaming from a high window.',
      'An abandoned observatory, massive telescope pointing at a sky visible through a collapsed dome roof, starry night.',
      'A decaying control room of a Soviet-era power plant, analog dials and buttons covered in dust and rust, cold war relic.',
      'An overgrown stone staircase leading to nowhere in a deep dark forest, covered in thick green moss, mysterious mood.',
      'A forgotten villa bedroom, a dusty canopy bed, rotting fabrics, old photos scattered on the floor, nostalgic sadness.'
    ],
    videos: [
      'Slow cinematic drone shot flying through a broken window into a decaying, overgrown grand ballroom.',
      'Camera moving slowly down a long, dark asylum corridor, peeling paint on walls, dust particles floating in light beams.',
      'Time-lapse of moss and ivy growing over a rusted typewriter on a dusty desk near a broken window.',
      'A slow pan across an abandoned amusement park, showing a rusted Ferris wheel creaking slightly in the wind.',
      'Drone shot flying over a massive rusted shipwreck stuck on a rocky shore, ocean waves crashing in slow motion.',
      'Camera slowly pushing in on a dusty old piano in a decaying hall, a single key slowly falling down on its own (spooky vibe).',
      'Walking view exploring an abandoned underground bunker, flashlight beam cutting through the pitch-black darkness.',
      'A slow tracking shot along rusted machinery in a massive, silent industrial factory, nature reclaiming the space.',
      'Time-lapse of light and shadows moving across a forgotten classroom with old wooden desks and a dusty blackboard.',
      'A drone rising up through the collapsed roof of an old church, revealing the forest surrounding the ruins.',
      'Camera panning down from a broken glass greenhouse dome to show wild ferns growing over rusty tables.',
      'Slow motion of dust swirling in a bright sunbeam inside a decaying library filled with rotting books.',
      'A slow slider shot of a rusted retro car covered in leaves inside a collapsing wooden garage.',
      'Walking down a grand staircase in a decaying mansion, debris crunching underfoot (implied audio), moody shadows.',
      'Camera rotating around a single rusted swing set moving slowly in the wind in an empty overgrown playground.',
      'A drone shot flying low along abandoned train tracks that disappear into a dark, overgrown forest tunnel.',
      'An old analog clock on a decaying wall, hands frozen, camera slowly zooming in on the dusty clock face.',
      'Slow pan of a forgotten theater hall, stage curtains swaying gently in a draft, light shining on dust.',
      'Exploring an old castle ruin at dusk, flashlight beam illuminating ancient stone carvings covered in moss.',
      'A slow tilt shift video of a abandoned radar station on a mountain peak, clouds passing rapidly behind it.'
    ]
  },
  {
    id: 'schloesser',
    name: 'Schlösser & Burgen',
    icon: '🏰',
    description: 'Thronsäle, historische Innenhöfe und sagenhafte Festungen.',
    images: [
      'A majestic medieval castle standing on a high cliff surrounded by autumn forests, morning mist, dramatic sunbeams, epic fantasy style.',
      'A luxury fairytale palace reflecting in a perfectly calm lake at sunset, pink and gold sky, elegant spires and towers.',
      'An ancient stone castle courtyard at night, torches lit, glowing windows, mysterious medieval atmosphere, starry sky.',
      'The grand library of a royal palace, tall wooden shelves filled with leather-bound books, rolling ladders, warm classical lighting.',
      'A ruined gothic castle under a dramatic thunderstorm sky, lightning bolt striking in the background, dark moody fantasy.',
      'The throne room of an emperor, golden ornaments, red velvet carpets, massive throne under a high arched window, cinematic.',
      'An aerial drone shot of a star-shaped renaissance fortress surrounded by a water moat, green lawns, symmetrical geometry.',
      'A grand dining hall in a castle, a long banquet table set with silver plates, candlesticks glowing, medieval feast vibe.',
      'A castle drawbridge lowering over a misty moat at sunrise, sun flare reflecting off the wet wood and iron chains.',
      'Close-up of a medieval stone fireplace crackling with fire inside a cozy castle chamber, tapestries on the walls.',
      'A winding stone spiral staircase inside a castle tower, light beaming from a narrow slit window, high contrast shadows.',
      'A beautiful white palace surrounded by manicured French gardens, fountains spraying water, bright sunny day, Versailles style.',
      'A historic castle gate guarded by stone gargoyles, iron portcullis half-open, misty forest pathway leading to it.',
      'The ruins of a hilltop castle at sunset, only stone arches standing, sky turning orange and red, cinematic silhouette.',
      'A royal bedroom in a palace, a four-poster gold bed with silk curtains, elegant classical paintings on the ceiling.',
      'A misty bridge leading to a fairytale castle in the middle of a lake, mystical fantasy mood, reflection on water.',
      'An ancient armory hall inside a castle, rows of shining knight armors holding swords, dim torchlight.',
      'A palace ballroom with polished marble floors reflecting crystal chandeliers, high gold-trimmed mirrors, royal elegance.',
      'A hidden secret door disguised as a bookshelf inside an old castle study, half-open, dark room visible behind.',
      'A dramatic winter shot of a castle covered in snow, standing tall against a dark blue twilight sky, warm lights in windows.'
    ],
    videos: [
      'Drone flyover of a fairytale castle perched on a rocky mountain peak, fog drifting through the valley below at sunrise.',
      'Camera walking slowly through a grand palace corridor, passing massive paintings, gold frames, and marble columns.',
      'Drone shot descending into a castle courtyard, revealing a medieval market setup or knights preparing.',
      'A slow cinematic pan across a royal throne room, lighting up the golden details as sun rays break through the window.',
      'Time-lapse of a starry night sky moving above the ruins of a gothic castle on a hill.',
      'A camera tracking shot walking up a winding stone spiral staircase inside a dark castle tower, torch flickering.',
      'Drone view flying low over a palace water moat, reflecting the majestic castle towers in the morning light.',
      'Slow motion of a heavy iron drawbridge closing, chains rattling, dust rising from the stone ground.',
      'A slow pan of a grand palace ballroom, capturing the reflection of glowing chandeliers on the polished marble floor.',
      'Drone shot sweeping over a massive star fortress, highlighting the green grassy ramparts and surrounding water.',
      'A camera moving through the royal library, passing ancient books and a cozy fireplace burning in the corner.',
      'Lightning striking behind a ruined dark castle on a cliff, creating a dramatic and spooky silhouette.',
      'A slow tilt-up from a stone gargoyle statue to the massive wooden entrance gate of a medieval fortress.',
      'Camera floating through a castle garden maze, green hedges, revealing a beautiful palace in the center.',
      'Slow motion of a fire crackling in a massive stone fireplace inside a royal dining chamber.',
      'A drone shot circling a snow-covered castle at dusk, warm yellow lights glowing in the towers.',
      'A close-up of a wax seal being stamped onto a royal decree document inside a castle study room.',
      'Time-lapse of clouds moving rapidly over a cliffside castle during a colorful sunset.',
      'Camera tracking a person in a historical royal gown walking through a palace hallway, dress sweeping the floor.',
      'A slow dolly shot entering the armory hall, rows of knight armors standing in silent formation.'
    ]
  }
];
